// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/geowa4/rara-membership/ent/event"
	"github.com/geowa4/rara-membership/ent/member"
	"github.com/geowa4/rara-membership/ent/pointallocation"
	"github.com/geowa4/rara-membership/ent/pointdeduction"
	"github.com/geowa4/rara-membership/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescName is the schema descriptor for name field.
	eventDescName := eventFields[0].Descriptor()
	// event.NameValidator is a validator for the "name" field. It is called by the builders before save.
	event.NameValidator = eventDescName.Validators[0].(func(string) error)
	// eventDescDescription is the schema descriptor for description field.
	eventDescDescription := eventFields[1].Descriptor()
	// event.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	event.DescriptionValidator = eventDescDescription.Validators[0].(func(string) error)
	// eventDescDate is the schema descriptor for date field.
	eventDescDate := eventFields[2].Descriptor()
	// event.DefaultDate holds the default value on creation for the date field.
	event.DefaultDate = eventDescDate.Default.(func() time.Time)
	// eventDescTimezone is the schema descriptor for timezone field.
	eventDescTimezone := eventFields[3].Descriptor()
	// event.DefaultTimezone holds the default value on creation for the timezone field.
	event.DefaultTimezone = eventDescTimezone.Default.(string)
	// eventDescLatitude is the schema descriptor for latitude field.
	eventDescLatitude := eventFields[4].Descriptor()
	// event.DefaultLatitude holds the default value on creation for the latitude field.
	event.DefaultLatitude = eventDescLatitude.Default.(float64)
	// event.LatitudeValidator is a validator for the "latitude" field. It is called by the builders before save.
	event.LatitudeValidator = func() func(float64) error {
		validators := eventDescLatitude.Validators
		fns := [...]func(float64) error{
			validators[0].(func(float64) error),
			validators[1].(func(float64) error),
		}
		return func(latitude float64) error {
			for _, fn := range fns {
				if err := fn(latitude); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// eventDescLongitude is the schema descriptor for longitude field.
	eventDescLongitude := eventFields[5].Descriptor()
	// event.DefaultLongitude holds the default value on creation for the longitude field.
	event.DefaultLongitude = eventDescLongitude.Default.(float64)
	// event.LongitudeValidator is a validator for the "longitude" field. It is called by the builders before save.
	event.LongitudeValidator = func() func(float64) error {
		validators := eventDescLongitude.Validators
		fns := [...]func(float64) error{
			validators[0].(func(float64) error),
			validators[1].(func(float64) error),
		}
		return func(longitude float64) error {
			for _, fn := range fns {
				if err := fn(longitude); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// eventDescDefaultPointsAllocated is the schema descriptor for default_points_allocated field.
	eventDescDefaultPointsAllocated := eventFields[6].Descriptor()
	// event.DefaultDefaultPointsAllocated holds the default value on creation for the default_points_allocated field.
	event.DefaultDefaultPointsAllocated = eventDescDefaultPointsAllocated.Default.(int8)
	// event.DefaultPointsAllocatedValidator is a validator for the "default_points_allocated" field. It is called by the builders before save.
	event.DefaultPointsAllocatedValidator = func() func(int8) error {
		validators := eventDescDefaultPointsAllocated.Validators
		fns := [...]func(int8) error{
			validators[0].(func(int8) error),
			validators[1].(func(int8) error),
		}
		return func(default_points_allocated int8) error {
			for _, fn := range fns {
				if err := fn(default_points_allocated); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	memberHooks := schema.Member{}.Hooks()
	member.Hooks[0] = memberHooks[0]
	memberFields := schema.Member{}.Fields()
	_ = memberFields
	// memberDescEmail is the schema descriptor for email field.
	memberDescEmail := memberFields[1].Descriptor()
	// member.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	member.EmailValidator = memberDescEmail.Validators[0].(func(string) error)
	// memberDescIsActive is the schema descriptor for is_active field.
	memberDescIsActive := memberFields[6].Descriptor()
	// member.DefaultIsActive holds the default value on creation for the is_active field.
	member.DefaultIsActive = memberDescIsActive.Default.(bool)
	// memberDescIsSilentKey is the schema descriptor for is_silent_key field.
	memberDescIsSilentKey := memberFields[7].Descriptor()
	// member.DefaultIsSilentKey holds the default value on creation for the is_silent_key field.
	member.DefaultIsSilentKey = memberDescIsSilentKey.Default.(bool)
	// memberDescLicenseClass is the schema descriptor for license_class field.
	memberDescLicenseClass := memberFields[8].Descriptor()
	// member.LicenseClassValidator is a validator for the "license_class" field. It is called by the builders before save.
	member.LicenseClassValidator = memberDescLicenseClass.Validators[0].(func(string) error)
	pointallocationFields := schema.PointAllocation{}.Fields()
	_ = pointallocationFields
	// pointallocationDescPoints is the schema descriptor for points field.
	pointallocationDescPoints := pointallocationFields[0].Descriptor()
	// pointallocation.PointsValidator is a validator for the "points" field. It is called by the builders before save.
	pointallocation.PointsValidator = func() func(int) error {
		validators := pointallocationDescPoints.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(points int) error {
			for _, fn := range fns {
				if err := fn(points); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// pointallocationDescCreatedAt is the schema descriptor for created_at field.
	pointallocationDescCreatedAt := pointallocationFields[2].Descriptor()
	// pointallocation.DefaultCreatedAt holds the default value on creation for the created_at field.
	pointallocation.DefaultCreatedAt = pointallocationDescCreatedAt.Default.(func() time.Time)
	pointdeductionFields := schema.PointDeduction{}.Fields()
	_ = pointdeductionFields
	// pointdeductionDescPoints is the schema descriptor for points field.
	pointdeductionDescPoints := pointdeductionFields[0].Descriptor()
	// pointdeduction.PointsValidator is a validator for the "points" field. It is called by the builders before save.
	pointdeduction.PointsValidator = pointdeductionDescPoints.Validators[0].(func(int) error)
	// pointdeductionDescCreatedAt is the schema descriptor for created_at field.
	pointdeductionDescCreatedAt := pointdeductionFields[2].Descriptor()
	// pointdeduction.DefaultCreatedAt holds the default value on creation for the created_at field.
	pointdeduction.DefaultCreatedAt = pointdeductionDescCreatedAt.Default.(func() time.Time)
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
