// Code generated by ent, DO NOT EDIT.

package event

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the event type in the database.
	Label = "event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"
	// FieldLatitude holds the string denoting the latitude field in the database.
	FieldLatitude = "latitude"
	// FieldLongitude holds the string denoting the longitude field in the database.
	FieldLongitude = "longitude"
	// FieldDefaultPointsAllocated holds the string denoting the default_points_allocated field in the database.
	FieldDefaultPointsAllocated = "default_points_allocated"
	// EdgePointAllocations holds the string denoting the point_allocations edge name in mutations.
	EdgePointAllocations = "point_allocations"
	// Table holds the table name of the event in the database.
	Table = "events"
	// PointAllocationsTable is the table that holds the point_allocations relation/edge.
	PointAllocationsTable = "point_allocations"
	// PointAllocationsInverseTable is the table name for the PointAllocation entity.
	// It exists in this package in order to avoid circular dependency with the "pointallocation" package.
	PointAllocationsInverseTable = "point_allocations"
	// PointAllocationsColumn is the table column denoting the point_allocations relation/edge.
	PointAllocationsColumn = "point_allocation_event"
)

// Columns holds all SQL columns for event fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldDate,
	FieldLatitude,
	FieldLongitude,
	FieldDefaultPointsAllocated,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultDate holds the default value on creation for the "date" field.
	DefaultDate func() time.Time
	// DefaultLatitude holds the default value on creation for the "latitude" field.
	DefaultLatitude float64
	// LatitudeValidator is a validator for the "latitude" field. It is called by the builders before save.
	LatitudeValidator func(float64) error
	// DefaultLongitude holds the default value on creation for the "longitude" field.
	DefaultLongitude float64
	// LongitudeValidator is a validator for the "longitude" field. It is called by the builders before save.
	LongitudeValidator func(float64) error
	// DefaultDefaultPointsAllocated holds the default value on creation for the "default_points_allocated" field.
	DefaultDefaultPointsAllocated int8
	// DefaultPointsAllocatedValidator is a validator for the "default_points_allocated" field. It is called by the builders before save.
	DefaultPointsAllocatedValidator func(int8) error
)

// OrderOption defines the ordering options for the Event queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByDate orders the results by the date field.
func ByDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDate, opts...).ToFunc()
}

// ByLatitude orders the results by the latitude field.
func ByLatitude(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatitude, opts...).ToFunc()
}

// ByLongitude orders the results by the longitude field.
func ByLongitude(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLongitude, opts...).ToFunc()
}

// ByDefaultPointsAllocated orders the results by the default_points_allocated field.
func ByDefaultPointsAllocated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultPointsAllocated, opts...).ToFunc()
}

// ByPointAllocationsCount orders the results by point_allocations count.
func ByPointAllocationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPointAllocationsStep(), opts...)
	}
}

// ByPointAllocations orders the results by point_allocations terms.
func ByPointAllocations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPointAllocationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPointAllocationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PointAllocationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, PointAllocationsTable, PointAllocationsColumn),
	)
}
