// Code generated by ent, DO NOT EDIT.

package member

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the member type in the database.
	Label = "member"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldMailingAddress holds the string denoting the mailing_address field in the database.
	FieldMailingAddress = "mailing_address"
	// FieldCallSign holds the string denoting the call_sign field in the database.
	FieldCallSign = "call_sign"
	// FieldFrn holds the string denoting the frn field in the database.
	FieldFrn = "frn"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldIsSilentKey holds the string denoting the is_silent_key field in the database.
	FieldIsSilentKey = "is_silent_key"
	// FieldLicenseClass holds the string denoting the license_class field in the database.
	FieldLicenseClass = "license_class"
	// Table holds the table name of the member in the database.
	Table = "members"
)

// Columns holds all SQL columns for member fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldEmail,
	FieldPhone,
	FieldMailingAddress,
	FieldCallSign,
	FieldFrn,
	FieldIsActive,
	FieldIsSilentKey,
	FieldLicenseClass,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultIsSilentKey holds the default value on creation for the "is_silent_key" field.
	DefaultIsSilentKey bool
	// LicenseClassValidator is a validator for the "license_class" field. It is called by the builders before save.
	LicenseClassValidator func(string) error
)

// OrderOption defines the ordering options for the Member queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPhone orders the results by the phone field.
func ByPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhone, opts...).ToFunc()
}

// ByMailingAddress orders the results by the mailing_address field.
func ByMailingAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMailingAddress, opts...).ToFunc()
}

// ByCallSign orders the results by the call_sign field.
func ByCallSign(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCallSign, opts...).ToFunc()
}

// ByFrn orders the results by the frn field.
func ByFrn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrn, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByIsSilentKey orders the results by the is_silent_key field.
func ByIsSilentKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsSilentKey, opts...).ToFunc()
}

// ByLicenseClass orders the results by the license_class field.
func ByLicenseClass(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLicenseClass, opts...).ToFunc()
}
