// Code generated by ent, DO NOT EDIT.

package member

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the member type in the database.
	Label = "member"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldMailingAddress holds the string denoting the mailing_address field in the database.
	FieldMailingAddress = "mailing_address"
	// FieldCallSign holds the string denoting the call_sign field in the database.
	FieldCallSign = "call_sign"
	// FieldFrn holds the string denoting the frn field in the database.
	FieldFrn = "frn"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldMemberType holds the string denoting the member_type field in the database.
	FieldMemberType = "member_type"
	// FieldIsSilentKey holds the string denoting the is_silent_key field in the database.
	FieldIsSilentKey = "is_silent_key"
	// FieldLicenseClass holds the string denoting the license_class field in the database.
	FieldLicenseClass = "license_class"
	// EdgePointAllocations holds the string denoting the point_allocations edge name in mutations.
	EdgePointAllocations = "point_allocations"
	// EdgePointDeductions holds the string denoting the point_deductions edge name in mutations.
	EdgePointDeductions = "point_deductions"
	// Table holds the table name of the member in the database.
	Table = "members"
	// PointAllocationsTable is the table that holds the point_allocations relation/edge.
	PointAllocationsTable = "point_allocations"
	// PointAllocationsInverseTable is the table name for the PointAllocation entity.
	// It exists in this package in order to avoid circular dependency with the "pointallocation" package.
	PointAllocationsInverseTable = "point_allocations"
	// PointAllocationsColumn is the table column denoting the point_allocations relation/edge.
	PointAllocationsColumn = "point_allocation_member"
	// PointDeductionsTable is the table that holds the point_deductions relation/edge.
	PointDeductionsTable = "point_deductions"
	// PointDeductionsInverseTable is the table name for the PointDeduction entity.
	// It exists in this package in order to avoid circular dependency with the "pointdeduction" package.
	PointDeductionsInverseTable = "point_deductions"
	// PointDeductionsColumn is the table column denoting the point_deductions relation/edge.
	PointDeductionsColumn = "point_deduction_member"
)

// Columns holds all SQL columns for member fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldEmail,
	FieldPhone,
	FieldMailingAddress,
	FieldCallSign,
	FieldFrn,
	FieldIsActive,
	FieldMemberType,
	FieldIsSilentKey,
	FieldLicenseClass,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/geowa4/rara-membership/ent/runtime"
var (
	Hooks [1]ent.Hook
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// MemberTypeValidator is a validator for the "member_type" field. It is called by the builders before save.
	MemberTypeValidator func(string) error
	// DefaultIsSilentKey holds the default value on creation for the "is_silent_key" field.
	DefaultIsSilentKey bool
	// LicenseClassValidator is a validator for the "license_class" field. It is called by the builders before save.
	LicenseClassValidator func(string) error
)

// OrderOption defines the ordering options for the Member queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPhone orders the results by the phone field.
func ByPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhone, opts...).ToFunc()
}

// ByMailingAddress orders the results by the mailing_address field.
func ByMailingAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMailingAddress, opts...).ToFunc()
}

// ByCallSign orders the results by the call_sign field.
func ByCallSign(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCallSign, opts...).ToFunc()
}

// ByFrn orders the results by the frn field.
func ByFrn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrn, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByMemberType orders the results by the member_type field.
func ByMemberType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemberType, opts...).ToFunc()
}

// ByIsSilentKey orders the results by the is_silent_key field.
func ByIsSilentKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsSilentKey, opts...).ToFunc()
}

// ByLicenseClass orders the results by the license_class field.
func ByLicenseClass(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLicenseClass, opts...).ToFunc()
}

// ByPointAllocationsCount orders the results by point_allocations count.
func ByPointAllocationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPointAllocationsStep(), opts...)
	}
}

// ByPointAllocations orders the results by point_allocations terms.
func ByPointAllocations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPointAllocationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPointDeductionsCount orders the results by point_deductions count.
func ByPointDeductionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPointDeductionsStep(), opts...)
	}
}

// ByPointDeductions orders the results by point_deductions terms.
func ByPointDeductions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPointDeductionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPointAllocationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PointAllocationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, PointAllocationsTable, PointAllocationsColumn),
	)
}
func newPointDeductionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PointDeductionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, PointDeductionsTable, PointDeductionsColumn),
	)
}
