// Code generated by ent, DO NOT EDIT.

package member

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/geowa4/rara-membership/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Member {
	return predicate.Member(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Member {
	return predicate.Member(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Member {
	return predicate.Member(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Member {
	return predicate.Member(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Member {
	return predicate.Member(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Member {
	return predicate.Member(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Member {
	return predicate.Member(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldName, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldEmail, v))
}

// Phone applies equality check predicate on the "phone" field. It's identical to PhoneEQ.
func Phone(v string) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldPhone, v))
}

// MailingAddress applies equality check predicate on the "mailing_address" field. It's identical to MailingAddressEQ.
func MailingAddress(v string) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldMailingAddress, v))
}

// CallSign applies equality check predicate on the "call_sign" field. It's identical to CallSignEQ.
func CallSign(v string) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldCallSign, v))
}

// Frn applies equality check predicate on the "frn" field. It's identical to FrnEQ.
func Frn(v string) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldFrn, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldIsActive, v))
}

// IsSilentKey applies equality check predicate on the "is_silent_key" field. It's identical to IsSilentKeyEQ.
func IsSilentKey(v bool) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldIsSilentKey, v))
}

// LicenseClass applies equality check predicate on the "license_class" field. It's identical to LicenseClassEQ.
func LicenseClass(v string) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldLicenseClass, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Member {
	return predicate.Member(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Member {
	return predicate.Member(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Member {
	return predicate.Member(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Member {
	return predicate.Member(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Member {
	return predicate.Member(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Member {
	return predicate.Member(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Member {
	return predicate.Member(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Member {
	return predicate.Member(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Member {
	return predicate.Member(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Member {
	return predicate.Member(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Member {
	return predicate.Member(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Member {
	return predicate.Member(sql.FieldContainsFold(FieldName, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.Member {
	return predicate.Member(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.Member {
	return predicate.Member(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.Member {
	return predicate.Member(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.Member {
	return predicate.Member(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.Member {
	return predicate.Member(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.Member {
	return predicate.Member(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.Member {
	return predicate.Member(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.Member {
	return predicate.Member(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.Member {
	return predicate.Member(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.Member {
	return predicate.Member(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.Member {
	return predicate.Member(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.Member {
	return predicate.Member(sql.FieldContainsFold(FieldEmail, v))
}

// PhoneEQ applies the EQ predicate on the "phone" field.
func PhoneEQ(v string) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldPhone, v))
}

// PhoneNEQ applies the NEQ predicate on the "phone" field.
func PhoneNEQ(v string) predicate.Member {
	return predicate.Member(sql.FieldNEQ(FieldPhone, v))
}

// PhoneIn applies the In predicate on the "phone" field.
func PhoneIn(vs ...string) predicate.Member {
	return predicate.Member(sql.FieldIn(FieldPhone, vs...))
}

// PhoneNotIn applies the NotIn predicate on the "phone" field.
func PhoneNotIn(vs ...string) predicate.Member {
	return predicate.Member(sql.FieldNotIn(FieldPhone, vs...))
}

// PhoneGT applies the GT predicate on the "phone" field.
func PhoneGT(v string) predicate.Member {
	return predicate.Member(sql.FieldGT(FieldPhone, v))
}

// PhoneGTE applies the GTE predicate on the "phone" field.
func PhoneGTE(v string) predicate.Member {
	return predicate.Member(sql.FieldGTE(FieldPhone, v))
}

// PhoneLT applies the LT predicate on the "phone" field.
func PhoneLT(v string) predicate.Member {
	return predicate.Member(sql.FieldLT(FieldPhone, v))
}

// PhoneLTE applies the LTE predicate on the "phone" field.
func PhoneLTE(v string) predicate.Member {
	return predicate.Member(sql.FieldLTE(FieldPhone, v))
}

// PhoneContains applies the Contains predicate on the "phone" field.
func PhoneContains(v string) predicate.Member {
	return predicate.Member(sql.FieldContains(FieldPhone, v))
}

// PhoneHasPrefix applies the HasPrefix predicate on the "phone" field.
func PhoneHasPrefix(v string) predicate.Member {
	return predicate.Member(sql.FieldHasPrefix(FieldPhone, v))
}

// PhoneHasSuffix applies the HasSuffix predicate on the "phone" field.
func PhoneHasSuffix(v string) predicate.Member {
	return predicate.Member(sql.FieldHasSuffix(FieldPhone, v))
}

// PhoneIsNil applies the IsNil predicate on the "phone" field.
func PhoneIsNil() predicate.Member {
	return predicate.Member(sql.FieldIsNull(FieldPhone))
}

// PhoneNotNil applies the NotNil predicate on the "phone" field.
func PhoneNotNil() predicate.Member {
	return predicate.Member(sql.FieldNotNull(FieldPhone))
}

// PhoneEqualFold applies the EqualFold predicate on the "phone" field.
func PhoneEqualFold(v string) predicate.Member {
	return predicate.Member(sql.FieldEqualFold(FieldPhone, v))
}

// PhoneContainsFold applies the ContainsFold predicate on the "phone" field.
func PhoneContainsFold(v string) predicate.Member {
	return predicate.Member(sql.FieldContainsFold(FieldPhone, v))
}

// MailingAddressEQ applies the EQ predicate on the "mailing_address" field.
func MailingAddressEQ(v string) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldMailingAddress, v))
}

// MailingAddressNEQ applies the NEQ predicate on the "mailing_address" field.
func MailingAddressNEQ(v string) predicate.Member {
	return predicate.Member(sql.FieldNEQ(FieldMailingAddress, v))
}

// MailingAddressIn applies the In predicate on the "mailing_address" field.
func MailingAddressIn(vs ...string) predicate.Member {
	return predicate.Member(sql.FieldIn(FieldMailingAddress, vs...))
}

// MailingAddressNotIn applies the NotIn predicate on the "mailing_address" field.
func MailingAddressNotIn(vs ...string) predicate.Member {
	return predicate.Member(sql.FieldNotIn(FieldMailingAddress, vs...))
}

// MailingAddressGT applies the GT predicate on the "mailing_address" field.
func MailingAddressGT(v string) predicate.Member {
	return predicate.Member(sql.FieldGT(FieldMailingAddress, v))
}

// MailingAddressGTE applies the GTE predicate on the "mailing_address" field.
func MailingAddressGTE(v string) predicate.Member {
	return predicate.Member(sql.FieldGTE(FieldMailingAddress, v))
}

// MailingAddressLT applies the LT predicate on the "mailing_address" field.
func MailingAddressLT(v string) predicate.Member {
	return predicate.Member(sql.FieldLT(FieldMailingAddress, v))
}

// MailingAddressLTE applies the LTE predicate on the "mailing_address" field.
func MailingAddressLTE(v string) predicate.Member {
	return predicate.Member(sql.FieldLTE(FieldMailingAddress, v))
}

// MailingAddressContains applies the Contains predicate on the "mailing_address" field.
func MailingAddressContains(v string) predicate.Member {
	return predicate.Member(sql.FieldContains(FieldMailingAddress, v))
}

// MailingAddressHasPrefix applies the HasPrefix predicate on the "mailing_address" field.
func MailingAddressHasPrefix(v string) predicate.Member {
	return predicate.Member(sql.FieldHasPrefix(FieldMailingAddress, v))
}

// MailingAddressHasSuffix applies the HasSuffix predicate on the "mailing_address" field.
func MailingAddressHasSuffix(v string) predicate.Member {
	return predicate.Member(sql.FieldHasSuffix(FieldMailingAddress, v))
}

// MailingAddressIsNil applies the IsNil predicate on the "mailing_address" field.
func MailingAddressIsNil() predicate.Member {
	return predicate.Member(sql.FieldIsNull(FieldMailingAddress))
}

// MailingAddressNotNil applies the NotNil predicate on the "mailing_address" field.
func MailingAddressNotNil() predicate.Member {
	return predicate.Member(sql.FieldNotNull(FieldMailingAddress))
}

// MailingAddressEqualFold applies the EqualFold predicate on the "mailing_address" field.
func MailingAddressEqualFold(v string) predicate.Member {
	return predicate.Member(sql.FieldEqualFold(FieldMailingAddress, v))
}

// MailingAddressContainsFold applies the ContainsFold predicate on the "mailing_address" field.
func MailingAddressContainsFold(v string) predicate.Member {
	return predicate.Member(sql.FieldContainsFold(FieldMailingAddress, v))
}

// CallSignEQ applies the EQ predicate on the "call_sign" field.
func CallSignEQ(v string) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldCallSign, v))
}

// CallSignNEQ applies the NEQ predicate on the "call_sign" field.
func CallSignNEQ(v string) predicate.Member {
	return predicate.Member(sql.FieldNEQ(FieldCallSign, v))
}

// CallSignIn applies the In predicate on the "call_sign" field.
func CallSignIn(vs ...string) predicate.Member {
	return predicate.Member(sql.FieldIn(FieldCallSign, vs...))
}

// CallSignNotIn applies the NotIn predicate on the "call_sign" field.
func CallSignNotIn(vs ...string) predicate.Member {
	return predicate.Member(sql.FieldNotIn(FieldCallSign, vs...))
}

// CallSignGT applies the GT predicate on the "call_sign" field.
func CallSignGT(v string) predicate.Member {
	return predicate.Member(sql.FieldGT(FieldCallSign, v))
}

// CallSignGTE applies the GTE predicate on the "call_sign" field.
func CallSignGTE(v string) predicate.Member {
	return predicate.Member(sql.FieldGTE(FieldCallSign, v))
}

// CallSignLT applies the LT predicate on the "call_sign" field.
func CallSignLT(v string) predicate.Member {
	return predicate.Member(sql.FieldLT(FieldCallSign, v))
}

// CallSignLTE applies the LTE predicate on the "call_sign" field.
func CallSignLTE(v string) predicate.Member {
	return predicate.Member(sql.FieldLTE(FieldCallSign, v))
}

// CallSignContains applies the Contains predicate on the "call_sign" field.
func CallSignContains(v string) predicate.Member {
	return predicate.Member(sql.FieldContains(FieldCallSign, v))
}

// CallSignHasPrefix applies the HasPrefix predicate on the "call_sign" field.
func CallSignHasPrefix(v string) predicate.Member {
	return predicate.Member(sql.FieldHasPrefix(FieldCallSign, v))
}

// CallSignHasSuffix applies the HasSuffix predicate on the "call_sign" field.
func CallSignHasSuffix(v string) predicate.Member {
	return predicate.Member(sql.FieldHasSuffix(FieldCallSign, v))
}

// CallSignIsNil applies the IsNil predicate on the "call_sign" field.
func CallSignIsNil() predicate.Member {
	return predicate.Member(sql.FieldIsNull(FieldCallSign))
}

// CallSignNotNil applies the NotNil predicate on the "call_sign" field.
func CallSignNotNil() predicate.Member {
	return predicate.Member(sql.FieldNotNull(FieldCallSign))
}

// CallSignEqualFold applies the EqualFold predicate on the "call_sign" field.
func CallSignEqualFold(v string) predicate.Member {
	return predicate.Member(sql.FieldEqualFold(FieldCallSign, v))
}

// CallSignContainsFold applies the ContainsFold predicate on the "call_sign" field.
func CallSignContainsFold(v string) predicate.Member {
	return predicate.Member(sql.FieldContainsFold(FieldCallSign, v))
}

// FrnEQ applies the EQ predicate on the "frn" field.
func FrnEQ(v string) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldFrn, v))
}

// FrnNEQ applies the NEQ predicate on the "frn" field.
func FrnNEQ(v string) predicate.Member {
	return predicate.Member(sql.FieldNEQ(FieldFrn, v))
}

// FrnIn applies the In predicate on the "frn" field.
func FrnIn(vs ...string) predicate.Member {
	return predicate.Member(sql.FieldIn(FieldFrn, vs...))
}

// FrnNotIn applies the NotIn predicate on the "frn" field.
func FrnNotIn(vs ...string) predicate.Member {
	return predicate.Member(sql.FieldNotIn(FieldFrn, vs...))
}

// FrnGT applies the GT predicate on the "frn" field.
func FrnGT(v string) predicate.Member {
	return predicate.Member(sql.FieldGT(FieldFrn, v))
}

// FrnGTE applies the GTE predicate on the "frn" field.
func FrnGTE(v string) predicate.Member {
	return predicate.Member(sql.FieldGTE(FieldFrn, v))
}

// FrnLT applies the LT predicate on the "frn" field.
func FrnLT(v string) predicate.Member {
	return predicate.Member(sql.FieldLT(FieldFrn, v))
}

// FrnLTE applies the LTE predicate on the "frn" field.
func FrnLTE(v string) predicate.Member {
	return predicate.Member(sql.FieldLTE(FieldFrn, v))
}

// FrnContains applies the Contains predicate on the "frn" field.
func FrnContains(v string) predicate.Member {
	return predicate.Member(sql.FieldContains(FieldFrn, v))
}

// FrnHasPrefix applies the HasPrefix predicate on the "frn" field.
func FrnHasPrefix(v string) predicate.Member {
	return predicate.Member(sql.FieldHasPrefix(FieldFrn, v))
}

// FrnHasSuffix applies the HasSuffix predicate on the "frn" field.
func FrnHasSuffix(v string) predicate.Member {
	return predicate.Member(sql.FieldHasSuffix(FieldFrn, v))
}

// FrnIsNil applies the IsNil predicate on the "frn" field.
func FrnIsNil() predicate.Member {
	return predicate.Member(sql.FieldIsNull(FieldFrn))
}

// FrnNotNil applies the NotNil predicate on the "frn" field.
func FrnNotNil() predicate.Member {
	return predicate.Member(sql.FieldNotNull(FieldFrn))
}

// FrnEqualFold applies the EqualFold predicate on the "frn" field.
func FrnEqualFold(v string) predicate.Member {
	return predicate.Member(sql.FieldEqualFold(FieldFrn, v))
}

// FrnContainsFold applies the ContainsFold predicate on the "frn" field.
func FrnContainsFold(v string) predicate.Member {
	return predicate.Member(sql.FieldContainsFold(FieldFrn, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.Member {
	return predicate.Member(sql.FieldNEQ(FieldIsActive, v))
}

// IsSilentKeyEQ applies the EQ predicate on the "is_silent_key" field.
func IsSilentKeyEQ(v bool) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldIsSilentKey, v))
}

// IsSilentKeyNEQ applies the NEQ predicate on the "is_silent_key" field.
func IsSilentKeyNEQ(v bool) predicate.Member {
	return predicate.Member(sql.FieldNEQ(FieldIsSilentKey, v))
}

// LicenseClassEQ applies the EQ predicate on the "license_class" field.
func LicenseClassEQ(v string) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldLicenseClass, v))
}

// LicenseClassNEQ applies the NEQ predicate on the "license_class" field.
func LicenseClassNEQ(v string) predicate.Member {
	return predicate.Member(sql.FieldNEQ(FieldLicenseClass, v))
}

// LicenseClassIn applies the In predicate on the "license_class" field.
func LicenseClassIn(vs ...string) predicate.Member {
	return predicate.Member(sql.FieldIn(FieldLicenseClass, vs...))
}

// LicenseClassNotIn applies the NotIn predicate on the "license_class" field.
func LicenseClassNotIn(vs ...string) predicate.Member {
	return predicate.Member(sql.FieldNotIn(FieldLicenseClass, vs...))
}

// LicenseClassGT applies the GT predicate on the "license_class" field.
func LicenseClassGT(v string) predicate.Member {
	return predicate.Member(sql.FieldGT(FieldLicenseClass, v))
}

// LicenseClassGTE applies the GTE predicate on the "license_class" field.
func LicenseClassGTE(v string) predicate.Member {
	return predicate.Member(sql.FieldGTE(FieldLicenseClass, v))
}

// LicenseClassLT applies the LT predicate on the "license_class" field.
func LicenseClassLT(v string) predicate.Member {
	return predicate.Member(sql.FieldLT(FieldLicenseClass, v))
}

// LicenseClassLTE applies the LTE predicate on the "license_class" field.
func LicenseClassLTE(v string) predicate.Member {
	return predicate.Member(sql.FieldLTE(FieldLicenseClass, v))
}

// LicenseClassContains applies the Contains predicate on the "license_class" field.
func LicenseClassContains(v string) predicate.Member {
	return predicate.Member(sql.FieldContains(FieldLicenseClass, v))
}

// LicenseClassHasPrefix applies the HasPrefix predicate on the "license_class" field.
func LicenseClassHasPrefix(v string) predicate.Member {
	return predicate.Member(sql.FieldHasPrefix(FieldLicenseClass, v))
}

// LicenseClassHasSuffix applies the HasSuffix predicate on the "license_class" field.
func LicenseClassHasSuffix(v string) predicate.Member {
	return predicate.Member(sql.FieldHasSuffix(FieldLicenseClass, v))
}

// LicenseClassIsNil applies the IsNil predicate on the "license_class" field.
func LicenseClassIsNil() predicate.Member {
	return predicate.Member(sql.FieldIsNull(FieldLicenseClass))
}

// LicenseClassNotNil applies the NotNil predicate on the "license_class" field.
func LicenseClassNotNil() predicate.Member {
	return predicate.Member(sql.FieldNotNull(FieldLicenseClass))
}

// LicenseClassEqualFold applies the EqualFold predicate on the "license_class" field.
func LicenseClassEqualFold(v string) predicate.Member {
	return predicate.Member(sql.FieldEqualFold(FieldLicenseClass, v))
}

// LicenseClassContainsFold applies the ContainsFold predicate on the "license_class" field.
func LicenseClassContainsFold(v string) predicate.Member {
	return predicate.Member(sql.FieldContainsFold(FieldLicenseClass, v))
}

// HasPointAllocations applies the HasEdge predicate on the "point_allocations" edge.
func HasPointAllocations() predicate.Member {
	return predicate.Member(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, PointAllocationsTable, PointAllocationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPointAllocationsWith applies the HasEdge predicate on the "point_allocations" edge with a given conditions (other predicates).
func HasPointAllocationsWith(preds ...predicate.PointAllocation) predicate.Member {
	return predicate.Member(func(s *sql.Selector) {
		step := newPointAllocationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPointDeductions applies the HasEdge predicate on the "point_deductions" edge.
func HasPointDeductions() predicate.Member {
	return predicate.Member(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, PointDeductionsTable, PointDeductionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPointDeductionsWith applies the HasEdge predicate on the "point_deductions" edge with a given conditions (other predicates).
func HasPointDeductionsWith(preds ...predicate.PointDeduction) predicate.Member {
	return predicate.Member(func(s *sql.Selector) {
		step := newPointDeductionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Member) predicate.Member {
	return predicate.Member(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Member) predicate.Member {
	return predicate.Member(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Member) predicate.Member {
	return predicate.Member(sql.NotPredicates(p))
}
