// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EventsColumns holds the columns for the "events" table.
	EventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "date", Type: field.TypeTime},
		{Name: "timezone", Type: field.TypeString, Default: "America/New_York"},
		{Name: "latitude", Type: field.TypeFloat64, Default: 43.138},
		{Name: "longitude", Type: field.TypeFloat64, Default: -77.572},
		{Name: "default_points_allocated", Type: field.TypeInt8, Default: 10},
	}
	// EventsTable holds the schema information for the "events" table.
	EventsTable = &schema.Table{
		Name:       "events",
		Columns:    EventsColumns,
		PrimaryKey: []*schema.Column{EventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "event_date",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[3]},
				Annotation: &entsql.IndexAnnotation{
					Desc: true,
				},
			},
		},
	}
	// MembersColumns holds the columns for the "members" table.
	MembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "mailing_address", Type: field.TypeString, Nullable: true},
		{Name: "call_sign", Type: field.TypeString, Nullable: true},
		{Name: "frn", Type: field.TypeString, Nullable: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "is_silent_key", Type: field.TypeBool, Default: false},
		{Name: "license_class", Type: field.TypeString, Nullable: true},
	}
	// MembersTable holds the schema information for the "members" table.
	MembersTable = &schema.Table{
		Name:       "members",
		Columns:    MembersColumns,
		PrimaryKey: []*schema.Column{MembersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "member_call_sign_is_active",
				Unique:  false,
				Columns: []*schema.Column{MembersColumns[5], MembersColumns[7]},
			},
			{
				Name:    "member_call_sign",
				Unique:  true,
				Columns: []*schema.Column{MembersColumns[5]},
				Annotation: &entsql.IndexAnnotation{
					Where: "is_active = true",
				},
			},
		},
	}
	// PointAllocationsColumns holds the columns for the "point_allocations" table.
	PointAllocationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "points", Type: field.TypeInt},
		{Name: "notes", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "point_allocation_event", Type: field.TypeInt},
		{Name: "point_allocation_member", Type: field.TypeInt},
	}
	// PointAllocationsTable holds the schema information for the "point_allocations" table.
	PointAllocationsTable = &schema.Table{
		Name:       "point_allocations",
		Columns:    PointAllocationsColumns,
		PrimaryKey: []*schema.Column{PointAllocationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "point_allocations_events_event",
				Columns:    []*schema.Column{PointAllocationsColumns[4]},
				RefColumns: []*schema.Column{EventsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "point_allocations_members_member",
				Columns:    []*schema.Column{PointAllocationsColumns[5]},
				RefColumns: []*schema.Column{MembersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "pointallocation_point_allocation_event_point_allocation_member",
				Unique:  true,
				Columns: []*schema.Column{PointAllocationsColumns[4], PointAllocationsColumns[5]},
			},
		},
	}
	// PointDeductionsColumns holds the columns for the "point_deductions" table.
	PointDeductionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "points", Type: field.TypeInt},
		{Name: "notes", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "point_deduction_member", Type: field.TypeInt},
	}
	// PointDeductionsTable holds the schema information for the "point_deductions" table.
	PointDeductionsTable = &schema.Table{
		Name:       "point_deductions",
		Columns:    PointDeductionsColumns,
		PrimaryKey: []*schema.Column{PointDeductionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "point_deductions_members_member",
				Columns:    []*schema.Column{PointDeductionsColumns[4]},
				RefColumns: []*schema.Column{MembersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EventsTable,
		MembersTable,
		PointAllocationsTable,
		PointDeductionsTable,
	}
)

func init() {
	PointAllocationsTable.ForeignKeys[0].RefTable = EventsTable
	PointAllocationsTable.ForeignKeys[1].RefTable = MembersTable
	PointDeductionsTable.ForeignKeys[0].RefTable = MembersTable
}
