// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/geowa4/rara-membership/ent/event"
	"github.com/geowa4/rara-membership/ent/pointallocation"
)

// EventCreate is the builder for creating a Event entity.
type EventCreate struct {
	config
	mutation *EventMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *EventCreate) SetName(v string) *EventCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *EventCreate) SetDescription(v string) *EventCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetDate sets the "date" field.
func (_c *EventCreate) SetDate(v time.Time) *EventCreate {
	_c.mutation.SetDate(v)
	return _c
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_c *EventCreate) SetNillableDate(v *time.Time) *EventCreate {
	if v != nil {
		_c.SetDate(*v)
	}
	return _c
}

// SetLatitude sets the "latitude" field.
func (_c *EventCreate) SetLatitude(v float64) *EventCreate {
	_c.mutation.SetLatitude(v)
	return _c
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_c *EventCreate) SetNillableLatitude(v *float64) *EventCreate {
	if v != nil {
		_c.SetLatitude(*v)
	}
	return _c
}

// SetLongitude sets the "longitude" field.
func (_c *EventCreate) SetLongitude(v float64) *EventCreate {
	_c.mutation.SetLongitude(v)
	return _c
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_c *EventCreate) SetNillableLongitude(v *float64) *EventCreate {
	if v != nil {
		_c.SetLongitude(*v)
	}
	return _c
}

// SetDefaultPointsAllocated sets the "default_points_allocated" field.
func (_c *EventCreate) SetDefaultPointsAllocated(v int8) *EventCreate {
	_c.mutation.SetDefaultPointsAllocated(v)
	return _c
}

// SetNillableDefaultPointsAllocated sets the "default_points_allocated" field if the given value is not nil.
func (_c *EventCreate) SetNillableDefaultPointsAllocated(v *int8) *EventCreate {
	if v != nil {
		_c.SetDefaultPointsAllocated(*v)
	}
	return _c
}

// AddPointAllocationIDs adds the "point_allocations" edge to the PointAllocation entity by IDs.
func (_c *EventCreate) AddPointAllocationIDs(ids ...int) *EventCreate {
	_c.mutation.AddPointAllocationIDs(ids...)
	return _c
}

// AddPointAllocations adds the "point_allocations" edges to the PointAllocation entity.
func (_c *EventCreate) AddPointAllocations(v ...*PointAllocation) *EventCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPointAllocationIDs(ids...)
}

// Mutation returns the EventMutation object of the builder.
func (_c *EventCreate) Mutation() *EventMutation {
	return _c.mutation
}

// Save creates the Event in the database.
func (_c *EventCreate) Save(ctx context.Context) (*Event, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EventCreate) SaveX(ctx context.Context) *Event {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EventCreate) defaults() {
	if _, ok := _c.mutation.Date(); !ok {
		v := event.DefaultDate()
		_c.mutation.SetDate(v)
	}
	if _, ok := _c.mutation.Latitude(); !ok {
		v := event.DefaultLatitude
		_c.mutation.SetLatitude(v)
	}
	if _, ok := _c.mutation.Longitude(); !ok {
		v := event.DefaultLongitude
		_c.mutation.SetLongitude(v)
	}
	if _, ok := _c.mutation.DefaultPointsAllocated(); !ok {
		v := event.DefaultDefaultPointsAllocated
		_c.mutation.SetDefaultPointsAllocated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EventCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Event.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := event.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Event.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Event.description"`)}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := event.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Event.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "Event.date"`)}
	}
	if _, ok := _c.mutation.Latitude(); !ok {
		return &ValidationError{Name: "latitude", err: errors.New(`ent: missing required field "Event.latitude"`)}
	}
	if v, ok := _c.mutation.Latitude(); ok {
		if err := event.LatitudeValidator(v); err != nil {
			return &ValidationError{Name: "latitude", err: fmt.Errorf(`ent: validator failed for field "Event.latitude": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Longitude(); !ok {
		return &ValidationError{Name: "longitude", err: errors.New(`ent: missing required field "Event.longitude"`)}
	}
	if v, ok := _c.mutation.Longitude(); ok {
		if err := event.LongitudeValidator(v); err != nil {
			return &ValidationError{Name: "longitude", err: fmt.Errorf(`ent: validator failed for field "Event.longitude": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DefaultPointsAllocated(); !ok {
		return &ValidationError{Name: "default_points_allocated", err: errors.New(`ent: missing required field "Event.default_points_allocated"`)}
	}
	if v, ok := _c.mutation.DefaultPointsAllocated(); ok {
		if err := event.DefaultPointsAllocatedValidator(v); err != nil {
			return &ValidationError{Name: "default_points_allocated", err: fmt.Errorf(`ent: validator failed for field "Event.default_points_allocated": %w`, err)}
		}
	}
	return nil
}

func (_c *EventCreate) sqlSave(ctx context.Context) (*Event, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EventCreate) createSpec() (*Event, *sqlgraph.CreateSpec) {
	var (
		_node = &Event{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(event.Table, sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(event.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(event.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Date(); ok {
		_spec.SetField(event.FieldDate, field.TypeTime, value)
		_node.Date = value
	}
	if value, ok := _c.mutation.Latitude(); ok {
		_spec.SetField(event.FieldLatitude, field.TypeFloat64, value)
		_node.Latitude = value
	}
	if value, ok := _c.mutation.Longitude(); ok {
		_spec.SetField(event.FieldLongitude, field.TypeFloat64, value)
		_node.Longitude = value
	}
	if value, ok := _c.mutation.DefaultPointsAllocated(); ok {
		_spec.SetField(event.FieldDefaultPointsAllocated, field.TypeInt8, value)
		_node.DefaultPointsAllocated = value
	}
	if nodes := _c.mutation.PointAllocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   event.PointAllocationsTable,
			Columns: []string{event.PointAllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointallocation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EventCreateBulk is the builder for creating many Event entities in bulk.
type EventCreateBulk struct {
	config
	err      error
	builders []*EventCreate
}

// Save creates the Event entities in the database.
func (_c *EventCreateBulk) Save(ctx context.Context) ([]*Event, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Event, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EventCreateBulk) SaveX(ctx context.Context) []*Event {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
