// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/geowa4/rara-membership/ent/event"
	"github.com/geowa4/rara-membership/ent/predicate"
)

// EventUpdate is the builder for updating Event entities.
type EventUpdate struct {
	config
	hooks    []Hook
	mutation *EventMutation
}

// Where appends a list predicates to the EventUpdate builder.
func (_u *EventUpdate) Where(ps ...predicate.Event) *EventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *EventUpdate) SetName(v string) *EventUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EventUpdate) SetNillableName(v *string) *EventUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *EventUpdate) SetDescription(v string) *EventUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *EventUpdate) SetNillableDescription(v *string) *EventUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetDate sets the "date" field.
func (_u *EventUpdate) SetDate(v time.Time) *EventUpdate {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *EventUpdate) SetNillableDate(v *time.Time) *EventUpdate {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetLatitude sets the "latitude" field.
func (_u *EventUpdate) SetLatitude(v float64) *EventUpdate {
	_u.mutation.ResetLatitude()
	_u.mutation.SetLatitude(v)
	return _u
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_u *EventUpdate) SetNillableLatitude(v *float64) *EventUpdate {
	if v != nil {
		_u.SetLatitude(*v)
	}
	return _u
}

// AddLatitude adds value to the "latitude" field.
func (_u *EventUpdate) AddLatitude(v float64) *EventUpdate {
	_u.mutation.AddLatitude(v)
	return _u
}

// SetLongitude sets the "longitude" field.
func (_u *EventUpdate) SetLongitude(v float64) *EventUpdate {
	_u.mutation.ResetLongitude()
	_u.mutation.SetLongitude(v)
	return _u
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_u *EventUpdate) SetNillableLongitude(v *float64) *EventUpdate {
	if v != nil {
		_u.SetLongitude(*v)
	}
	return _u
}

// AddLongitude adds value to the "longitude" field.
func (_u *EventUpdate) AddLongitude(v float64) *EventUpdate {
	_u.mutation.AddLongitude(v)
	return _u
}

// SetDefaultPointsAllocated sets the "default_points_allocated" field.
func (_u *EventUpdate) SetDefaultPointsAllocated(v int8) *EventUpdate {
	_u.mutation.ResetDefaultPointsAllocated()
	_u.mutation.SetDefaultPointsAllocated(v)
	return _u
}

// SetNillableDefaultPointsAllocated sets the "default_points_allocated" field if the given value is not nil.
func (_u *EventUpdate) SetNillableDefaultPointsAllocated(v *int8) *EventUpdate {
	if v != nil {
		_u.SetDefaultPointsAllocated(*v)
	}
	return _u
}

// AddDefaultPointsAllocated adds value to the "default_points_allocated" field.
func (_u *EventUpdate) AddDefaultPointsAllocated(v int8) *EventUpdate {
	_u.mutation.AddDefaultPointsAllocated(v)
	return _u
}

// Mutation returns the EventMutation object of the builder.
func (_u *EventUpdate) Mutation() *EventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := event.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Event.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := event.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Event.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Latitude(); ok {
		if err := event.LatitudeValidator(v); err != nil {
			return &ValidationError{Name: "latitude", err: fmt.Errorf(`ent: validator failed for field "Event.latitude": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Longitude(); ok {
		if err := event.LongitudeValidator(v); err != nil {
			return &ValidationError{Name: "longitude", err: fmt.Errorf(`ent: validator failed for field "Event.longitude": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultPointsAllocated(); ok {
		if err := event.DefaultPointsAllocatedValidator(v); err != nil {
			return &ValidationError{Name: "default_points_allocated", err: fmt.Errorf(`ent: validator failed for field "Event.default_points_allocated": %w`, err)}
		}
	}
	return nil
}

func (_u *EventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(event.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(event.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(event.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Latitude(); ok {
		_spec.SetField(event.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLatitude(); ok {
		_spec.AddField(event.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Longitude(); ok {
		_spec.SetField(event.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLongitude(); ok {
		_spec.AddField(event.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DefaultPointsAllocated(); ok {
		_spec.SetField(event.FieldDefaultPointsAllocated, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedDefaultPointsAllocated(); ok {
		_spec.AddField(event.FieldDefaultPointsAllocated, field.TypeInt8, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EventUpdateOne is the builder for updating a single Event entity.
type EventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventMutation
}

// SetName sets the "name" field.
func (_u *EventUpdateOne) SetName(v string) *EventUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableName(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *EventUpdateOne) SetDescription(v string) *EventUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableDescription(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetDate sets the "date" field.
func (_u *EventUpdateOne) SetDate(v time.Time) *EventUpdateOne {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableDate(v *time.Time) *EventUpdateOne {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetLatitude sets the "latitude" field.
func (_u *EventUpdateOne) SetLatitude(v float64) *EventUpdateOne {
	_u.mutation.ResetLatitude()
	_u.mutation.SetLatitude(v)
	return _u
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableLatitude(v *float64) *EventUpdateOne {
	if v != nil {
		_u.SetLatitude(*v)
	}
	return _u
}

// AddLatitude adds value to the "latitude" field.
func (_u *EventUpdateOne) AddLatitude(v float64) *EventUpdateOne {
	_u.mutation.AddLatitude(v)
	return _u
}

// SetLongitude sets the "longitude" field.
func (_u *EventUpdateOne) SetLongitude(v float64) *EventUpdateOne {
	_u.mutation.ResetLongitude()
	_u.mutation.SetLongitude(v)
	return _u
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableLongitude(v *float64) *EventUpdateOne {
	if v != nil {
		_u.SetLongitude(*v)
	}
	return _u
}

// AddLongitude adds value to the "longitude" field.
func (_u *EventUpdateOne) AddLongitude(v float64) *EventUpdateOne {
	_u.mutation.AddLongitude(v)
	return _u
}

// SetDefaultPointsAllocated sets the "default_points_allocated" field.
func (_u *EventUpdateOne) SetDefaultPointsAllocated(v int8) *EventUpdateOne {
	_u.mutation.ResetDefaultPointsAllocated()
	_u.mutation.SetDefaultPointsAllocated(v)
	return _u
}

// SetNillableDefaultPointsAllocated sets the "default_points_allocated" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableDefaultPointsAllocated(v *int8) *EventUpdateOne {
	if v != nil {
		_u.SetDefaultPointsAllocated(*v)
	}
	return _u
}

// AddDefaultPointsAllocated adds value to the "default_points_allocated" field.
func (_u *EventUpdateOne) AddDefaultPointsAllocated(v int8) *EventUpdateOne {
	_u.mutation.AddDefaultPointsAllocated(v)
	return _u
}

// Mutation returns the EventMutation object of the builder.
func (_u *EventUpdateOne) Mutation() *EventMutation {
	return _u.mutation
}

// Where appends a list predicates to the EventUpdate builder.
func (_u *EventUpdateOne) Where(ps ...predicate.Event) *EventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EventUpdateOne) Select(field string, fields ...string) *EventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Event entity.
func (_u *EventUpdateOne) Save(ctx context.Context) (*Event, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventUpdateOne) SaveX(ctx context.Context) *Event {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := event.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Event.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := event.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Event.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Latitude(); ok {
		if err := event.LatitudeValidator(v); err != nil {
			return &ValidationError{Name: "latitude", err: fmt.Errorf(`ent: validator failed for field "Event.latitude": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Longitude(); ok {
		if err := event.LongitudeValidator(v); err != nil {
			return &ValidationError{Name: "longitude", err: fmt.Errorf(`ent: validator failed for field "Event.longitude": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultPointsAllocated(); ok {
		if err := event.DefaultPointsAllocatedValidator(v); err != nil {
			return &ValidationError{Name: "default_points_allocated", err: fmt.Errorf(`ent: validator failed for field "Event.default_points_allocated": %w`, err)}
		}
	}
	return nil
}

func (_u *EventUpdateOne) sqlSave(ctx context.Context) (_node *Event, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Event.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, event.FieldID)
		for _, f := range fields {
			if !event.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != event.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(event.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(event.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(event.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Latitude(); ok {
		_spec.SetField(event.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLatitude(); ok {
		_spec.AddField(event.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Longitude(); ok {
		_spec.SetField(event.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLongitude(); ok {
		_spec.AddField(event.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DefaultPointsAllocated(); ok {
		_spec.SetField(event.FieldDefaultPointsAllocated, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedDefaultPointsAllocated(); ok {
		_spec.AddField(event.FieldDefaultPointsAllocated, field.TypeInt8, value)
	}
	_node = &Event{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
