// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/geowa4/rara-membership/ent/member"
	"github.com/geowa4/rara-membership/ent/predicate"
)

// MemberUpdate is the builder for updating Member entities.
type MemberUpdate struct {
	config
	hooks    []Hook
	mutation *MemberMutation
}

// Where appends a list predicates to the MemberUpdate builder.
func (_u *MemberUpdate) Where(ps ...predicate.Member) *MemberUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *MemberUpdate) SetName(v string) *MemberUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MemberUpdate) SetNillableName(v *string) *MemberUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *MemberUpdate) SetEmail(v string) *MemberUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *MemberUpdate) SetNillableEmail(v *string) *MemberUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *MemberUpdate) SetPhone(v string) *MemberUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *MemberUpdate) SetNillablePhone(v *string) *MemberUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// SetCallSign sets the "call_sign" field.
func (_u *MemberUpdate) SetCallSign(v string) *MemberUpdate {
	_u.mutation.SetCallSign(v)
	return _u
}

// SetNillableCallSign sets the "call_sign" field if the given value is not nil.
func (_u *MemberUpdate) SetNillableCallSign(v *string) *MemberUpdate {
	if v != nil {
		_u.SetCallSign(*v)
	}
	return _u
}

// SetFrn sets the "frn" field.
func (_u *MemberUpdate) SetFrn(v string) *MemberUpdate {
	_u.mutation.SetFrn(v)
	return _u
}

// SetNillableFrn sets the "frn" field if the given value is not nil.
func (_u *MemberUpdate) SetNillableFrn(v *string) *MemberUpdate {
	if v != nil {
		_u.SetFrn(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *MemberUpdate) SetIsActive(v bool) *MemberUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *MemberUpdate) SetNillableIsActive(v *bool) *MemberUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetIsSilentKey sets the "is_silent_key" field.
func (_u *MemberUpdate) SetIsSilentKey(v bool) *MemberUpdate {
	_u.mutation.SetIsSilentKey(v)
	return _u
}

// SetNillableIsSilentKey sets the "is_silent_key" field if the given value is not nil.
func (_u *MemberUpdate) SetNillableIsSilentKey(v *bool) *MemberUpdate {
	if v != nil {
		_u.SetIsSilentKey(*v)
	}
	return _u
}

// Mutation returns the MemberMutation object of the builder.
func (_u *MemberUpdate) Mutation() *MemberMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MemberUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MemberUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MemberUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(member.Table, member.Columns, sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(member.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(member.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(member.FieldPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.CallSign(); ok {
		_spec.SetField(member.FieldCallSign, field.TypeString, value)
	}
	if value, ok := _u.mutation.Frn(); ok {
		_spec.SetField(member.FieldFrn, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(member.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsSilentKey(); ok {
		_spec.SetField(member.FieldIsSilentKey, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{member.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MemberUpdateOne is the builder for updating a single Member entity.
type MemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MemberMutation
}

// SetName sets the "name" field.
func (_u *MemberUpdateOne) SetName(v string) *MemberUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MemberUpdateOne) SetNillableName(v *string) *MemberUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *MemberUpdateOne) SetEmail(v string) *MemberUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *MemberUpdateOne) SetNillableEmail(v *string) *MemberUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *MemberUpdateOne) SetPhone(v string) *MemberUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *MemberUpdateOne) SetNillablePhone(v *string) *MemberUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// SetCallSign sets the "call_sign" field.
func (_u *MemberUpdateOne) SetCallSign(v string) *MemberUpdateOne {
	_u.mutation.SetCallSign(v)
	return _u
}

// SetNillableCallSign sets the "call_sign" field if the given value is not nil.
func (_u *MemberUpdateOne) SetNillableCallSign(v *string) *MemberUpdateOne {
	if v != nil {
		_u.SetCallSign(*v)
	}
	return _u
}

// SetFrn sets the "frn" field.
func (_u *MemberUpdateOne) SetFrn(v string) *MemberUpdateOne {
	_u.mutation.SetFrn(v)
	return _u
}

// SetNillableFrn sets the "frn" field if the given value is not nil.
func (_u *MemberUpdateOne) SetNillableFrn(v *string) *MemberUpdateOne {
	if v != nil {
		_u.SetFrn(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *MemberUpdateOne) SetIsActive(v bool) *MemberUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *MemberUpdateOne) SetNillableIsActive(v *bool) *MemberUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetIsSilentKey sets the "is_silent_key" field.
func (_u *MemberUpdateOne) SetIsSilentKey(v bool) *MemberUpdateOne {
	_u.mutation.SetIsSilentKey(v)
	return _u
}

// SetNillableIsSilentKey sets the "is_silent_key" field if the given value is not nil.
func (_u *MemberUpdateOne) SetNillableIsSilentKey(v *bool) *MemberUpdateOne {
	if v != nil {
		_u.SetIsSilentKey(*v)
	}
	return _u
}

// Mutation returns the MemberMutation object of the builder.
func (_u *MemberUpdateOne) Mutation() *MemberMutation {
	return _u.mutation
}

// Where appends a list predicates to the MemberUpdate builder.
func (_u *MemberUpdateOne) Where(ps ...predicate.Member) *MemberUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MemberUpdateOne) Select(field string, fields ...string) *MemberUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Member entity.
func (_u *MemberUpdateOne) Save(ctx context.Context) (*Member, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberUpdateOne) SaveX(ctx context.Context) *Member {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MemberUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MemberUpdateOne) sqlSave(ctx context.Context) (_node *Member, err error) {
	_spec := sqlgraph.NewUpdateSpec(member.Table, member.Columns, sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Member.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, member.FieldID)
		for _, f := range fields {
			if !member.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != member.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(member.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(member.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(member.FieldPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.CallSign(); ok {
		_spec.SetField(member.FieldCallSign, field.TypeString, value)
	}
	if value, ok := _u.mutation.Frn(); ok {
		_spec.SetField(member.FieldFrn, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(member.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsSilentKey(); ok {
		_spec.SetField(member.FieldIsSilentKey, field.TypeBool, value)
	}
	_node = &Member{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{member.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
