// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/geowa4/rara-membership/ent/member"
)

// Member is the model entity for the Member schema.
type Member struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Phone holds the value of the "phone" field.
	Phone string `json:"phone,omitempty"`
	// MailingAddress holds the value of the "mailing_address" field.
	MailingAddress string `json:"mailing_address,omitempty"`
	// CallSign holds the value of the "call_sign" field.
	CallSign string `json:"call_sign,omitempty"`
	// Frn holds the value of the "frn" field.
	Frn string `json:"frn,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// MemberType holds the value of the "member_type" field.
	MemberType string `json:"member_type,omitempty"`
	// IsSilentKey holds the value of the "is_silent_key" field.
	IsSilentKey bool `json:"is_silent_key,omitempty"`
	// LicenseClass holds the value of the "license_class" field.
	LicenseClass string `json:"license_class,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MemberQuery when eager-loading is set.
	Edges        MemberEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MemberEdges holds the relations/edges for other nodes in the graph.
type MemberEdges struct {
	// Point allocations received by this member
	PointAllocations []*PointAllocation `json:"point_allocations,omitempty"`
	// Point deductions for redemptions by this member
	PointDeductions []*PointDeduction `json:"point_deductions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PointAllocationsOrErr returns the PointAllocations value or an error if the edge
// was not loaded in eager-loading.
func (e MemberEdges) PointAllocationsOrErr() ([]*PointAllocation, error) {
	if e.loadedTypes[0] {
		return e.PointAllocations, nil
	}
	return nil, &NotLoadedError{edge: "point_allocations"}
}

// PointDeductionsOrErr returns the PointDeductions value or an error if the edge
// was not loaded in eager-loading.
func (e MemberEdges) PointDeductionsOrErr() ([]*PointDeduction, error) {
	if e.loadedTypes[1] {
		return e.PointDeductions, nil
	}
	return nil, &NotLoadedError{edge: "point_deductions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Member) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case member.FieldIsActive, member.FieldIsSilentKey:
			values[i] = new(sql.NullBool)
		case member.FieldID:
			values[i] = new(sql.NullInt64)
		case member.FieldName, member.FieldEmail, member.FieldPhone, member.FieldMailingAddress, member.FieldCallSign, member.FieldFrn, member.FieldMemberType, member.FieldLicenseClass:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Member fields.
func (_m *Member) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case member.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case member.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case member.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case member.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				_m.Phone = value.String
			}
		case member.FieldMailingAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mailing_address", values[i])
			} else if value.Valid {
				_m.MailingAddress = value.String
			}
		case member.FieldCallSign:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field call_sign", values[i])
			} else if value.Valid {
				_m.CallSign = value.String
			}
		case member.FieldFrn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field frn", values[i])
			} else if value.Valid {
				_m.Frn = value.String
			}
		case member.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case member.FieldMemberType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field member_type", values[i])
			} else if value.Valid {
				_m.MemberType = value.String
			}
		case member.FieldIsSilentKey:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_silent_key", values[i])
			} else if value.Valid {
				_m.IsSilentKey = value.Bool
			}
		case member.FieldLicenseClass:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field license_class", values[i])
			} else if value.Valid {
				_m.LicenseClass = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Member.
// This includes values selected through modifiers, order, etc.
func (_m *Member) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPointAllocations queries the "point_allocations" edge of the Member entity.
func (_m *Member) QueryPointAllocations() *PointAllocationQuery {
	return NewMemberClient(_m.config).QueryPointAllocations(_m)
}

// QueryPointDeductions queries the "point_deductions" edge of the Member entity.
func (_m *Member) QueryPointDeductions() *PointDeductionQuery {
	return NewMemberClient(_m.config).QueryPointDeductions(_m)
}

// Update returns a builder for updating this Member.
// Note that you need to call Member.Unwrap() before calling this method if this Member
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Member) Update() *MemberUpdateOne {
	return NewMemberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Member entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Member) Unwrap() *Member {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Member is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Member) String() string {
	var builder strings.Builder
	builder.WriteString("Member(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("phone=")
	builder.WriteString(_m.Phone)
	builder.WriteString(", ")
	builder.WriteString("mailing_address=")
	builder.WriteString(_m.MailingAddress)
	builder.WriteString(", ")
	builder.WriteString("call_sign=")
	builder.WriteString(_m.CallSign)
	builder.WriteString(", ")
	builder.WriteString("frn=")
	builder.WriteString(_m.Frn)
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("member_type=")
	builder.WriteString(_m.MemberType)
	builder.WriteString(", ")
	builder.WriteString("is_silent_key=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsSilentKey))
	builder.WriteString(", ")
	builder.WriteString("license_class=")
	builder.WriteString(_m.LicenseClass)
	builder.WriteByte(')')
	return builder.String()
}

// Members is a parsable slice of Member.
type Members []*Member
