// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/geowa4/rara-membership/ent/member"
	"github.com/geowa4/rara-membership/ent/pointallocation"
	"github.com/geowa4/rara-membership/ent/pointdeduction"
)

// MemberCreate is the builder for creating a Member entity.
type MemberCreate struct {
	config
	mutation *MemberMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *MemberCreate) SetName(v string) *MemberCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *MemberCreate) SetEmail(v string) *MemberCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetPhone sets the "phone" field.
func (_c *MemberCreate) SetPhone(v string) *MemberCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_c *MemberCreate) SetNillablePhone(v *string) *MemberCreate {
	if v != nil {
		_c.SetPhone(*v)
	}
	return _c
}

// SetMailingAddress sets the "mailing_address" field.
func (_c *MemberCreate) SetMailingAddress(v string) *MemberCreate {
	_c.mutation.SetMailingAddress(v)
	return _c
}

// SetNillableMailingAddress sets the "mailing_address" field if the given value is not nil.
func (_c *MemberCreate) SetNillableMailingAddress(v *string) *MemberCreate {
	if v != nil {
		_c.SetMailingAddress(*v)
	}
	return _c
}

// SetCallSign sets the "call_sign" field.
func (_c *MemberCreate) SetCallSign(v string) *MemberCreate {
	_c.mutation.SetCallSign(v)
	return _c
}

// SetNillableCallSign sets the "call_sign" field if the given value is not nil.
func (_c *MemberCreate) SetNillableCallSign(v *string) *MemberCreate {
	if v != nil {
		_c.SetCallSign(*v)
	}
	return _c
}

// SetFrn sets the "frn" field.
func (_c *MemberCreate) SetFrn(v string) *MemberCreate {
	_c.mutation.SetFrn(v)
	return _c
}

// SetNillableFrn sets the "frn" field if the given value is not nil.
func (_c *MemberCreate) SetNillableFrn(v *string) *MemberCreate {
	if v != nil {
		_c.SetFrn(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *MemberCreate) SetIsActive(v bool) *MemberCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *MemberCreate) SetNillableIsActive(v *bool) *MemberCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetMemberType sets the "member_type" field.
func (_c *MemberCreate) SetMemberType(v string) *MemberCreate {
	_c.mutation.SetMemberType(v)
	return _c
}

// SetNillableMemberType sets the "member_type" field if the given value is not nil.
func (_c *MemberCreate) SetNillableMemberType(v *string) *MemberCreate {
	if v != nil {
		_c.SetMemberType(*v)
	}
	return _c
}

// SetIsSilentKey sets the "is_silent_key" field.
func (_c *MemberCreate) SetIsSilentKey(v bool) *MemberCreate {
	_c.mutation.SetIsSilentKey(v)
	return _c
}

// SetNillableIsSilentKey sets the "is_silent_key" field if the given value is not nil.
func (_c *MemberCreate) SetNillableIsSilentKey(v *bool) *MemberCreate {
	if v != nil {
		_c.SetIsSilentKey(*v)
	}
	return _c
}

// SetLicenseClass sets the "license_class" field.
func (_c *MemberCreate) SetLicenseClass(v string) *MemberCreate {
	_c.mutation.SetLicenseClass(v)
	return _c
}

// SetNillableLicenseClass sets the "license_class" field if the given value is not nil.
func (_c *MemberCreate) SetNillableLicenseClass(v *string) *MemberCreate {
	if v != nil {
		_c.SetLicenseClass(*v)
	}
	return _c
}

// AddPointAllocationIDs adds the "point_allocations" edge to the PointAllocation entity by IDs.
func (_c *MemberCreate) AddPointAllocationIDs(ids ...int) *MemberCreate {
	_c.mutation.AddPointAllocationIDs(ids...)
	return _c
}

// AddPointAllocations adds the "point_allocations" edges to the PointAllocation entity.
func (_c *MemberCreate) AddPointAllocations(v ...*PointAllocation) *MemberCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPointAllocationIDs(ids...)
}

// AddPointDeductionIDs adds the "point_deductions" edge to the PointDeduction entity by IDs.
func (_c *MemberCreate) AddPointDeductionIDs(ids ...int) *MemberCreate {
	_c.mutation.AddPointDeductionIDs(ids...)
	return _c
}

// AddPointDeductions adds the "point_deductions" edges to the PointDeduction entity.
func (_c *MemberCreate) AddPointDeductions(v ...*PointDeduction) *MemberCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPointDeductionIDs(ids...)
}

// Mutation returns the MemberMutation object of the builder.
func (_c *MemberCreate) Mutation() *MemberMutation {
	return _c.mutation
}

// Save creates the Member in the database.
func (_c *MemberCreate) Save(ctx context.Context) (*Member, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MemberCreate) SaveX(ctx context.Context) *Member {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MemberCreate) defaults() error {
	if _, ok := _c.mutation.IsActive(); !ok {
		v := member.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.IsSilentKey(); !ok {
		v := member.DefaultIsSilentKey
		_c.mutation.SetIsSilentKey(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *MemberCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Member.name"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Member.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := member.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Member.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Member.is_active"`)}
	}
	if v, ok := _c.mutation.MemberType(); ok {
		if err := member.MemberTypeValidator(v); err != nil {
			return &ValidationError{Name: "member_type", err: fmt.Errorf(`ent: validator failed for field "Member.member_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsSilentKey(); !ok {
		return &ValidationError{Name: "is_silent_key", err: errors.New(`ent: missing required field "Member.is_silent_key"`)}
	}
	if v, ok := _c.mutation.LicenseClass(); ok {
		if err := member.LicenseClassValidator(v); err != nil {
			return &ValidationError{Name: "license_class", err: fmt.Errorf(`ent: validator failed for field "Member.license_class": %w`, err)}
		}
	}
	return nil
}

func (_c *MemberCreate) sqlSave(ctx context.Context) (*Member, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MemberCreate) createSpec() (*Member, *sqlgraph.CreateSpec) {
	var (
		_node = &Member{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(member.Table, sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(member.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(member.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(member.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.MailingAddress(); ok {
		_spec.SetField(member.FieldMailingAddress, field.TypeString, value)
		_node.MailingAddress = value
	}
	if value, ok := _c.mutation.CallSign(); ok {
		_spec.SetField(member.FieldCallSign, field.TypeString, value)
		_node.CallSign = value
	}
	if value, ok := _c.mutation.Frn(); ok {
		_spec.SetField(member.FieldFrn, field.TypeString, value)
		_node.Frn = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(member.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.MemberType(); ok {
		_spec.SetField(member.FieldMemberType, field.TypeString, value)
		_node.MemberType = value
	}
	if value, ok := _c.mutation.IsSilentKey(); ok {
		_spec.SetField(member.FieldIsSilentKey, field.TypeBool, value)
		_node.IsSilentKey = value
	}
	if value, ok := _c.mutation.LicenseClass(); ok {
		_spec.SetField(member.FieldLicenseClass, field.TypeString, value)
		_node.LicenseClass = value
	}
	if nodes := _c.mutation.PointAllocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   member.PointAllocationsTable,
			Columns: []string{member.PointAllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointallocation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PointDeductionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   member.PointDeductionsTable,
			Columns: []string{member.PointDeductionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointdeduction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MemberCreateBulk is the builder for creating many Member entities in bulk.
type MemberCreateBulk struct {
	config
	err      error
	builders []*MemberCreate
}

// Save creates the Member entities in the database.
func (_c *MemberCreateBulk) Save(ctx context.Context) ([]*Member, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Member, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MemberCreateBulk) SaveX(ctx context.Context) []*Member {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
