// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/geowa4/rara-membership/ent/member"
	"github.com/geowa4/rara-membership/ent/pointallocation"
	"github.com/geowa4/rara-membership/ent/pointdeduction"
	"github.com/geowa4/rara-membership/ent/predicate"
)

// MemberUpdate is the builder for updating Member entities.
type MemberUpdate struct {
	config
	hooks    []Hook
	mutation *MemberMutation
}

// Where appends a list predicates to the MemberUpdate builder.
func (_u *MemberUpdate) Where(ps ...predicate.Member) *MemberUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *MemberUpdate) SetName(v string) *MemberUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MemberUpdate) SetNillableName(v *string) *MemberUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *MemberUpdate) SetEmail(v string) *MemberUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *MemberUpdate) SetNillableEmail(v *string) *MemberUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *MemberUpdate) SetPhone(v string) *MemberUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *MemberUpdate) SetNillablePhone(v *string) *MemberUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *MemberUpdate) ClearPhone() *MemberUpdate {
	_u.mutation.ClearPhone()
	return _u
}

// SetMailingAddress sets the "mailing_address" field.
func (_u *MemberUpdate) SetMailingAddress(v string) *MemberUpdate {
	_u.mutation.SetMailingAddress(v)
	return _u
}

// SetNillableMailingAddress sets the "mailing_address" field if the given value is not nil.
func (_u *MemberUpdate) SetNillableMailingAddress(v *string) *MemberUpdate {
	if v != nil {
		_u.SetMailingAddress(*v)
	}
	return _u
}

// ClearMailingAddress clears the value of the "mailing_address" field.
func (_u *MemberUpdate) ClearMailingAddress() *MemberUpdate {
	_u.mutation.ClearMailingAddress()
	return _u
}

// SetCallSign sets the "call_sign" field.
func (_u *MemberUpdate) SetCallSign(v string) *MemberUpdate {
	_u.mutation.SetCallSign(v)
	return _u
}

// SetNillableCallSign sets the "call_sign" field if the given value is not nil.
func (_u *MemberUpdate) SetNillableCallSign(v *string) *MemberUpdate {
	if v != nil {
		_u.SetCallSign(*v)
	}
	return _u
}

// ClearCallSign clears the value of the "call_sign" field.
func (_u *MemberUpdate) ClearCallSign() *MemberUpdate {
	_u.mutation.ClearCallSign()
	return _u
}

// SetFrn sets the "frn" field.
func (_u *MemberUpdate) SetFrn(v string) *MemberUpdate {
	_u.mutation.SetFrn(v)
	return _u
}

// SetNillableFrn sets the "frn" field if the given value is not nil.
func (_u *MemberUpdate) SetNillableFrn(v *string) *MemberUpdate {
	if v != nil {
		_u.SetFrn(*v)
	}
	return _u
}

// ClearFrn clears the value of the "frn" field.
func (_u *MemberUpdate) ClearFrn() *MemberUpdate {
	_u.mutation.ClearFrn()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *MemberUpdate) SetIsActive(v bool) *MemberUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *MemberUpdate) SetNillableIsActive(v *bool) *MemberUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetIsSilentKey sets the "is_silent_key" field.
func (_u *MemberUpdate) SetIsSilentKey(v bool) *MemberUpdate {
	_u.mutation.SetIsSilentKey(v)
	return _u
}

// SetNillableIsSilentKey sets the "is_silent_key" field if the given value is not nil.
func (_u *MemberUpdate) SetNillableIsSilentKey(v *bool) *MemberUpdate {
	if v != nil {
		_u.SetIsSilentKey(*v)
	}
	return _u
}

// SetLicenseClass sets the "license_class" field.
func (_u *MemberUpdate) SetLicenseClass(v string) *MemberUpdate {
	_u.mutation.SetLicenseClass(v)
	return _u
}

// SetNillableLicenseClass sets the "license_class" field if the given value is not nil.
func (_u *MemberUpdate) SetNillableLicenseClass(v *string) *MemberUpdate {
	if v != nil {
		_u.SetLicenseClass(*v)
	}
	return _u
}

// ClearLicenseClass clears the value of the "license_class" field.
func (_u *MemberUpdate) ClearLicenseClass() *MemberUpdate {
	_u.mutation.ClearLicenseClass()
	return _u
}

// AddPointAllocationIDs adds the "point_allocations" edge to the PointAllocation entity by IDs.
func (_u *MemberUpdate) AddPointAllocationIDs(ids ...int) *MemberUpdate {
	_u.mutation.AddPointAllocationIDs(ids...)
	return _u
}

// AddPointAllocations adds the "point_allocations" edges to the PointAllocation entity.
func (_u *MemberUpdate) AddPointAllocations(v ...*PointAllocation) *MemberUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPointAllocationIDs(ids...)
}

// AddPointDeductionIDs adds the "point_deductions" edge to the PointDeduction entity by IDs.
func (_u *MemberUpdate) AddPointDeductionIDs(ids ...int) *MemberUpdate {
	_u.mutation.AddPointDeductionIDs(ids...)
	return _u
}

// AddPointDeductions adds the "point_deductions" edges to the PointDeduction entity.
func (_u *MemberUpdate) AddPointDeductions(v ...*PointDeduction) *MemberUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPointDeductionIDs(ids...)
}

// Mutation returns the MemberMutation object of the builder.
func (_u *MemberUpdate) Mutation() *MemberMutation {
	return _u.mutation
}

// ClearPointAllocations clears all "point_allocations" edges to the PointAllocation entity.
func (_u *MemberUpdate) ClearPointAllocations() *MemberUpdate {
	_u.mutation.ClearPointAllocations()
	return _u
}

// RemovePointAllocationIDs removes the "point_allocations" edge to PointAllocation entities by IDs.
func (_u *MemberUpdate) RemovePointAllocationIDs(ids ...int) *MemberUpdate {
	_u.mutation.RemovePointAllocationIDs(ids...)
	return _u
}

// RemovePointAllocations removes "point_allocations" edges to PointAllocation entities.
func (_u *MemberUpdate) RemovePointAllocations(v ...*PointAllocation) *MemberUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePointAllocationIDs(ids...)
}

// ClearPointDeductions clears all "point_deductions" edges to the PointDeduction entity.
func (_u *MemberUpdate) ClearPointDeductions() *MemberUpdate {
	_u.mutation.ClearPointDeductions()
	return _u
}

// RemovePointDeductionIDs removes the "point_deductions" edge to PointDeduction entities by IDs.
func (_u *MemberUpdate) RemovePointDeductionIDs(ids ...int) *MemberUpdate {
	_u.mutation.RemovePointDeductionIDs(ids...)
	return _u
}

// RemovePointDeductions removes "point_deductions" edges to PointDeduction entities.
func (_u *MemberUpdate) RemovePointDeductions(v ...*PointDeduction) *MemberUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePointDeductionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MemberUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MemberUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := member.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Member.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LicenseClass(); ok {
		if err := member.LicenseClassValidator(v); err != nil {
			return &ValidationError{Name: "license_class", err: fmt.Errorf(`ent: validator failed for field "Member.license_class": %w`, err)}
		}
	}
	return nil
}

func (_u *MemberUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(member.Table, member.Columns, sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(member.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(member.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(member.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(member.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.MailingAddress(); ok {
		_spec.SetField(member.FieldMailingAddress, field.TypeString, value)
	}
	if _u.mutation.MailingAddressCleared() {
		_spec.ClearField(member.FieldMailingAddress, field.TypeString)
	}
	if value, ok := _u.mutation.CallSign(); ok {
		_spec.SetField(member.FieldCallSign, field.TypeString, value)
	}
	if _u.mutation.CallSignCleared() {
		_spec.ClearField(member.FieldCallSign, field.TypeString)
	}
	if value, ok := _u.mutation.Frn(); ok {
		_spec.SetField(member.FieldFrn, field.TypeString, value)
	}
	if _u.mutation.FrnCleared() {
		_spec.ClearField(member.FieldFrn, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(member.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsSilentKey(); ok {
		_spec.SetField(member.FieldIsSilentKey, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LicenseClass(); ok {
		_spec.SetField(member.FieldLicenseClass, field.TypeString, value)
	}
	if _u.mutation.LicenseClassCleared() {
		_spec.ClearField(member.FieldLicenseClass, field.TypeString)
	}
	if _u.mutation.PointAllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   member.PointAllocationsTable,
			Columns: []string{member.PointAllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointallocation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPointAllocationsIDs(); len(nodes) > 0 && !_u.mutation.PointAllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   member.PointAllocationsTable,
			Columns: []string{member.PointAllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointallocation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PointAllocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   member.PointAllocationsTable,
			Columns: []string{member.PointAllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointallocation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PointDeductionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   member.PointDeductionsTable,
			Columns: []string{member.PointDeductionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointdeduction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPointDeductionsIDs(); len(nodes) > 0 && !_u.mutation.PointDeductionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   member.PointDeductionsTable,
			Columns: []string{member.PointDeductionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointdeduction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PointDeductionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   member.PointDeductionsTable,
			Columns: []string{member.PointDeductionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointdeduction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{member.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MemberUpdateOne is the builder for updating a single Member entity.
type MemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MemberMutation
}

// SetName sets the "name" field.
func (_u *MemberUpdateOne) SetName(v string) *MemberUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MemberUpdateOne) SetNillableName(v *string) *MemberUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *MemberUpdateOne) SetEmail(v string) *MemberUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *MemberUpdateOne) SetNillableEmail(v *string) *MemberUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *MemberUpdateOne) SetPhone(v string) *MemberUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *MemberUpdateOne) SetNillablePhone(v *string) *MemberUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *MemberUpdateOne) ClearPhone() *MemberUpdateOne {
	_u.mutation.ClearPhone()
	return _u
}

// SetMailingAddress sets the "mailing_address" field.
func (_u *MemberUpdateOne) SetMailingAddress(v string) *MemberUpdateOne {
	_u.mutation.SetMailingAddress(v)
	return _u
}

// SetNillableMailingAddress sets the "mailing_address" field if the given value is not nil.
func (_u *MemberUpdateOne) SetNillableMailingAddress(v *string) *MemberUpdateOne {
	if v != nil {
		_u.SetMailingAddress(*v)
	}
	return _u
}

// ClearMailingAddress clears the value of the "mailing_address" field.
func (_u *MemberUpdateOne) ClearMailingAddress() *MemberUpdateOne {
	_u.mutation.ClearMailingAddress()
	return _u
}

// SetCallSign sets the "call_sign" field.
func (_u *MemberUpdateOne) SetCallSign(v string) *MemberUpdateOne {
	_u.mutation.SetCallSign(v)
	return _u
}

// SetNillableCallSign sets the "call_sign" field if the given value is not nil.
func (_u *MemberUpdateOne) SetNillableCallSign(v *string) *MemberUpdateOne {
	if v != nil {
		_u.SetCallSign(*v)
	}
	return _u
}

// ClearCallSign clears the value of the "call_sign" field.
func (_u *MemberUpdateOne) ClearCallSign() *MemberUpdateOne {
	_u.mutation.ClearCallSign()
	return _u
}

// SetFrn sets the "frn" field.
func (_u *MemberUpdateOne) SetFrn(v string) *MemberUpdateOne {
	_u.mutation.SetFrn(v)
	return _u
}

// SetNillableFrn sets the "frn" field if the given value is not nil.
func (_u *MemberUpdateOne) SetNillableFrn(v *string) *MemberUpdateOne {
	if v != nil {
		_u.SetFrn(*v)
	}
	return _u
}

// ClearFrn clears the value of the "frn" field.
func (_u *MemberUpdateOne) ClearFrn() *MemberUpdateOne {
	_u.mutation.ClearFrn()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *MemberUpdateOne) SetIsActive(v bool) *MemberUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *MemberUpdateOne) SetNillableIsActive(v *bool) *MemberUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetIsSilentKey sets the "is_silent_key" field.
func (_u *MemberUpdateOne) SetIsSilentKey(v bool) *MemberUpdateOne {
	_u.mutation.SetIsSilentKey(v)
	return _u
}

// SetNillableIsSilentKey sets the "is_silent_key" field if the given value is not nil.
func (_u *MemberUpdateOne) SetNillableIsSilentKey(v *bool) *MemberUpdateOne {
	if v != nil {
		_u.SetIsSilentKey(*v)
	}
	return _u
}

// SetLicenseClass sets the "license_class" field.
func (_u *MemberUpdateOne) SetLicenseClass(v string) *MemberUpdateOne {
	_u.mutation.SetLicenseClass(v)
	return _u
}

// SetNillableLicenseClass sets the "license_class" field if the given value is not nil.
func (_u *MemberUpdateOne) SetNillableLicenseClass(v *string) *MemberUpdateOne {
	if v != nil {
		_u.SetLicenseClass(*v)
	}
	return _u
}

// ClearLicenseClass clears the value of the "license_class" field.
func (_u *MemberUpdateOne) ClearLicenseClass() *MemberUpdateOne {
	_u.mutation.ClearLicenseClass()
	return _u
}

// AddPointAllocationIDs adds the "point_allocations" edge to the PointAllocation entity by IDs.
func (_u *MemberUpdateOne) AddPointAllocationIDs(ids ...int) *MemberUpdateOne {
	_u.mutation.AddPointAllocationIDs(ids...)
	return _u
}

// AddPointAllocations adds the "point_allocations" edges to the PointAllocation entity.
func (_u *MemberUpdateOne) AddPointAllocations(v ...*PointAllocation) *MemberUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPointAllocationIDs(ids...)
}

// AddPointDeductionIDs adds the "point_deductions" edge to the PointDeduction entity by IDs.
func (_u *MemberUpdateOne) AddPointDeductionIDs(ids ...int) *MemberUpdateOne {
	_u.mutation.AddPointDeductionIDs(ids...)
	return _u
}

// AddPointDeductions adds the "point_deductions" edges to the PointDeduction entity.
func (_u *MemberUpdateOne) AddPointDeductions(v ...*PointDeduction) *MemberUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPointDeductionIDs(ids...)
}

// Mutation returns the MemberMutation object of the builder.
func (_u *MemberUpdateOne) Mutation() *MemberMutation {
	return _u.mutation
}

// ClearPointAllocations clears all "point_allocations" edges to the PointAllocation entity.
func (_u *MemberUpdateOne) ClearPointAllocations() *MemberUpdateOne {
	_u.mutation.ClearPointAllocations()
	return _u
}

// RemovePointAllocationIDs removes the "point_allocations" edge to PointAllocation entities by IDs.
func (_u *MemberUpdateOne) RemovePointAllocationIDs(ids ...int) *MemberUpdateOne {
	_u.mutation.RemovePointAllocationIDs(ids...)
	return _u
}

// RemovePointAllocations removes "point_allocations" edges to PointAllocation entities.
func (_u *MemberUpdateOne) RemovePointAllocations(v ...*PointAllocation) *MemberUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePointAllocationIDs(ids...)
}

// ClearPointDeductions clears all "point_deductions" edges to the PointDeduction entity.
func (_u *MemberUpdateOne) ClearPointDeductions() *MemberUpdateOne {
	_u.mutation.ClearPointDeductions()
	return _u
}

// RemovePointDeductionIDs removes the "point_deductions" edge to PointDeduction entities by IDs.
func (_u *MemberUpdateOne) RemovePointDeductionIDs(ids ...int) *MemberUpdateOne {
	_u.mutation.RemovePointDeductionIDs(ids...)
	return _u
}

// RemovePointDeductions removes "point_deductions" edges to PointDeduction entities.
func (_u *MemberUpdateOne) RemovePointDeductions(v ...*PointDeduction) *MemberUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePointDeductionIDs(ids...)
}

// Where appends a list predicates to the MemberUpdate builder.
func (_u *MemberUpdateOne) Where(ps ...predicate.Member) *MemberUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MemberUpdateOne) Select(field string, fields ...string) *MemberUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Member entity.
func (_u *MemberUpdateOne) Save(ctx context.Context) (*Member, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberUpdateOne) SaveX(ctx context.Context) *Member {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MemberUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := member.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Member.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LicenseClass(); ok {
		if err := member.LicenseClassValidator(v); err != nil {
			return &ValidationError{Name: "license_class", err: fmt.Errorf(`ent: validator failed for field "Member.license_class": %w`, err)}
		}
	}
	return nil
}

func (_u *MemberUpdateOne) sqlSave(ctx context.Context) (_node *Member, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(member.Table, member.Columns, sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Member.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, member.FieldID)
		for _, f := range fields {
			if !member.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != member.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(member.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(member.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(member.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(member.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.MailingAddress(); ok {
		_spec.SetField(member.FieldMailingAddress, field.TypeString, value)
	}
	if _u.mutation.MailingAddressCleared() {
		_spec.ClearField(member.FieldMailingAddress, field.TypeString)
	}
	if value, ok := _u.mutation.CallSign(); ok {
		_spec.SetField(member.FieldCallSign, field.TypeString, value)
	}
	if _u.mutation.CallSignCleared() {
		_spec.ClearField(member.FieldCallSign, field.TypeString)
	}
	if value, ok := _u.mutation.Frn(); ok {
		_spec.SetField(member.FieldFrn, field.TypeString, value)
	}
	if _u.mutation.FrnCleared() {
		_spec.ClearField(member.FieldFrn, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(member.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsSilentKey(); ok {
		_spec.SetField(member.FieldIsSilentKey, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LicenseClass(); ok {
		_spec.SetField(member.FieldLicenseClass, field.TypeString, value)
	}
	if _u.mutation.LicenseClassCleared() {
		_spec.ClearField(member.FieldLicenseClass, field.TypeString)
	}
	if _u.mutation.PointAllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   member.PointAllocationsTable,
			Columns: []string{member.PointAllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointallocation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPointAllocationsIDs(); len(nodes) > 0 && !_u.mutation.PointAllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   member.PointAllocationsTable,
			Columns: []string{member.PointAllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointallocation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PointAllocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   member.PointAllocationsTable,
			Columns: []string{member.PointAllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointallocation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PointDeductionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   member.PointDeductionsTable,
			Columns: []string{member.PointDeductionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointdeduction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPointDeductionsIDs(); len(nodes) > 0 && !_u.mutation.PointDeductionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   member.PointDeductionsTable,
			Columns: []string{member.PointDeductionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointdeduction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PointDeductionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   member.PointDeductionsTable,
			Columns: []string{member.PointDeductionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointdeduction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Member{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{member.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
