// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/geowa4/rara-membership/ent/event"
	"github.com/geowa4/rara-membership/ent/member"
	"github.com/geowa4/rara-membership/ent/pointallocation"
	"github.com/geowa4/rara-membership/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeEvent           = "Event"
	TypeMember          = "Member"
	TypePointAllocation = "PointAllocation"
)

// EventMutation represents an operation that mutates the Event nodes in the graph.
type EventMutation struct {
	config
	op                          Op
	typ                         string
	id                          *int
	name                        *string
	description                 *string
	date                        *time.Time
	latitude                    *float64
	addlatitude                 *float64
	longitude                   *float64
	addlongitude                *float64
	default_points_allocated    *int8
	adddefault_points_allocated *int8
	clearedFields               map[string]struct{}
	point_allocations           map[int]struct{}
	removedpoint_allocations    map[int]struct{}
	clearedpoint_allocations    bool
	done                        bool
	oldValue                    func(context.Context) (*Event, error)
	predicates                  []predicate.Event
}

var _ ent.Mutation = (*EventMutation)(nil)

// eventOption allows management of the mutation configuration using functional options.
type eventOption func(*EventMutation)

// newEventMutation creates new mutation for the Event entity.
func newEventMutation(c config, op Op, opts ...eventOption) *EventMutation {
	m := &EventMutation{
		config:        c,
		op:            op,
		typ:           TypeEvent,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withEventID sets the ID field of the mutation.
func withEventID(id int) eventOption {
	return func(m *EventMutation) {
		var (
			err   error
			once  sync.Once
			value *Event
		)
		m.oldValue = func(ctx context.Context) (*Event, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Event.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withEvent sets the old Event of the mutation.
func withEvent(node *Event) eventOption {
	return func(m *EventMutation) {
		m.oldValue = func(context.Context) (*Event, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m EventMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m EventMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *EventMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *EventMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Event.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *EventMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *EventMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Event entity.
// If the Event object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EventMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *EventMutation) ResetName() {
	m.name = nil
}

// SetDescription sets the "description" field.
func (m *EventMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *EventMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the Event entity.
// If the Event object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EventMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ResetDescription resets all changes to the "description" field.
func (m *EventMutation) ResetDescription() {
	m.description = nil
}

// SetDate sets the "date" field.
func (m *EventMutation) SetDate(t time.Time) {
	m.date = &t
}

// Date returns the value of the "date" field in the mutation.
func (m *EventMutation) Date() (r time.Time, exists bool) {
	v := m.date
	if v == nil {
		return
	}
	return *v, true
}

// OldDate returns the old "date" field's value of the Event entity.
// If the Event object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EventMutation) OldDate(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDate: %w", err)
	}
	return oldValue.Date, nil
}

// ResetDate resets all changes to the "date" field.
func (m *EventMutation) ResetDate() {
	m.date = nil
}

// SetLatitude sets the "latitude" field.
func (m *EventMutation) SetLatitude(f float64) {
	m.latitude = &f
	m.addlatitude = nil
}

// Latitude returns the value of the "latitude" field in the mutation.
func (m *EventMutation) Latitude() (r float64, exists bool) {
	v := m.latitude
	if v == nil {
		return
	}
	return *v, true
}

// OldLatitude returns the old "latitude" field's value of the Event entity.
// If the Event object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EventMutation) OldLatitude(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLatitude is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLatitude requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLatitude: %w", err)
	}
	return oldValue.Latitude, nil
}

// AddLatitude adds f to the "latitude" field.
func (m *EventMutation) AddLatitude(f float64) {
	if m.addlatitude != nil {
		*m.addlatitude += f
	} else {
		m.addlatitude = &f
	}
}

// AddedLatitude returns the value that was added to the "latitude" field in this mutation.
func (m *EventMutation) AddedLatitude() (r float64, exists bool) {
	v := m.addlatitude
	if v == nil {
		return
	}
	return *v, true
}

// ResetLatitude resets all changes to the "latitude" field.
func (m *EventMutation) ResetLatitude() {
	m.latitude = nil
	m.addlatitude = nil
}

// SetLongitude sets the "longitude" field.
func (m *EventMutation) SetLongitude(f float64) {
	m.longitude = &f
	m.addlongitude = nil
}

// Longitude returns the value of the "longitude" field in the mutation.
func (m *EventMutation) Longitude() (r float64, exists bool) {
	v := m.longitude
	if v == nil {
		return
	}
	return *v, true
}

// OldLongitude returns the old "longitude" field's value of the Event entity.
// If the Event object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EventMutation) OldLongitude(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLongitude is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLongitude requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLongitude: %w", err)
	}
	return oldValue.Longitude, nil
}

// AddLongitude adds f to the "longitude" field.
func (m *EventMutation) AddLongitude(f float64) {
	if m.addlongitude != nil {
		*m.addlongitude += f
	} else {
		m.addlongitude = &f
	}
}

// AddedLongitude returns the value that was added to the "longitude" field in this mutation.
func (m *EventMutation) AddedLongitude() (r float64, exists bool) {
	v := m.addlongitude
	if v == nil {
		return
	}
	return *v, true
}

// ResetLongitude resets all changes to the "longitude" field.
func (m *EventMutation) ResetLongitude() {
	m.longitude = nil
	m.addlongitude = nil
}

// SetDefaultPointsAllocated sets the "default_points_allocated" field.
func (m *EventMutation) SetDefaultPointsAllocated(i int8) {
	m.default_points_allocated = &i
	m.adddefault_points_allocated = nil
}

// DefaultPointsAllocated returns the value of the "default_points_allocated" field in the mutation.
func (m *EventMutation) DefaultPointsAllocated() (r int8, exists bool) {
	v := m.default_points_allocated
	if v == nil {
		return
	}
	return *v, true
}

// OldDefaultPointsAllocated returns the old "default_points_allocated" field's value of the Event entity.
// If the Event object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EventMutation) OldDefaultPointsAllocated(ctx context.Context) (v int8, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDefaultPointsAllocated is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDefaultPointsAllocated requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDefaultPointsAllocated: %w", err)
	}
	return oldValue.DefaultPointsAllocated, nil
}

// AddDefaultPointsAllocated adds i to the "default_points_allocated" field.
func (m *EventMutation) AddDefaultPointsAllocated(i int8) {
	if m.adddefault_points_allocated != nil {
		*m.adddefault_points_allocated += i
	} else {
		m.adddefault_points_allocated = &i
	}
}

// AddedDefaultPointsAllocated returns the value that was added to the "default_points_allocated" field in this mutation.
func (m *EventMutation) AddedDefaultPointsAllocated() (r int8, exists bool) {
	v := m.adddefault_points_allocated
	if v == nil {
		return
	}
	return *v, true
}

// ResetDefaultPointsAllocated resets all changes to the "default_points_allocated" field.
func (m *EventMutation) ResetDefaultPointsAllocated() {
	m.default_points_allocated = nil
	m.adddefault_points_allocated = nil
}

// AddPointAllocationIDs adds the "point_allocations" edge to the PointAllocation entity by ids.
func (m *EventMutation) AddPointAllocationIDs(ids ...int) {
	if m.point_allocations == nil {
		m.point_allocations = make(map[int]struct{})
	}
	for i := range ids {
		m.point_allocations[ids[i]] = struct{}{}
	}
}

// ClearPointAllocations clears the "point_allocations" edge to the PointAllocation entity.
func (m *EventMutation) ClearPointAllocations() {
	m.clearedpoint_allocations = true
}

// PointAllocationsCleared reports if the "point_allocations" edge to the PointAllocation entity was cleared.
func (m *EventMutation) PointAllocationsCleared() bool {
	return m.clearedpoint_allocations
}

// RemovePointAllocationIDs removes the "point_allocations" edge to the PointAllocation entity by IDs.
func (m *EventMutation) RemovePointAllocationIDs(ids ...int) {
	if m.removedpoint_allocations == nil {
		m.removedpoint_allocations = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.point_allocations, ids[i])
		m.removedpoint_allocations[ids[i]] = struct{}{}
	}
}

// RemovedPointAllocations returns the removed IDs of the "point_allocations" edge to the PointAllocation entity.
func (m *EventMutation) RemovedPointAllocationsIDs() (ids []int) {
	for id := range m.removedpoint_allocations {
		ids = append(ids, id)
	}
	return
}

// PointAllocationsIDs returns the "point_allocations" edge IDs in the mutation.
func (m *EventMutation) PointAllocationsIDs() (ids []int) {
	for id := range m.point_allocations {
		ids = append(ids, id)
	}
	return
}

// ResetPointAllocations resets all changes to the "point_allocations" edge.
func (m *EventMutation) ResetPointAllocations() {
	m.point_allocations = nil
	m.clearedpoint_allocations = false
	m.removedpoint_allocations = nil
}

// Where appends a list predicates to the EventMutation builder.
func (m *EventMutation) Where(ps ...predicate.Event) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the EventMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *EventMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Event, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *EventMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *EventMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Event).
func (m *EventMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *EventMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.name != nil {
		fields = append(fields, event.FieldName)
	}
	if m.description != nil {
		fields = append(fields, event.FieldDescription)
	}
	if m.date != nil {
		fields = append(fields, event.FieldDate)
	}
	if m.latitude != nil {
		fields = append(fields, event.FieldLatitude)
	}
	if m.longitude != nil {
		fields = append(fields, event.FieldLongitude)
	}
	if m.default_points_allocated != nil {
		fields = append(fields, event.FieldDefaultPointsAllocated)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *EventMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case event.FieldName:
		return m.Name()
	case event.FieldDescription:
		return m.Description()
	case event.FieldDate:
		return m.Date()
	case event.FieldLatitude:
		return m.Latitude()
	case event.FieldLongitude:
		return m.Longitude()
	case event.FieldDefaultPointsAllocated:
		return m.DefaultPointsAllocated()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *EventMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case event.FieldName:
		return m.OldName(ctx)
	case event.FieldDescription:
		return m.OldDescription(ctx)
	case event.FieldDate:
		return m.OldDate(ctx)
	case event.FieldLatitude:
		return m.OldLatitude(ctx)
	case event.FieldLongitude:
		return m.OldLongitude(ctx)
	case event.FieldDefaultPointsAllocated:
		return m.OldDefaultPointsAllocated(ctx)
	}
	return nil, fmt.Errorf("unknown Event field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *EventMutation) SetField(name string, value ent.Value) error {
	switch name {
	case event.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case event.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case event.FieldDate:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDate(v)
		return nil
	case event.FieldLatitude:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLatitude(v)
		return nil
	case event.FieldLongitude:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLongitude(v)
		return nil
	case event.FieldDefaultPointsAllocated:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDefaultPointsAllocated(v)
		return nil
	}
	return fmt.Errorf("unknown Event field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *EventMutation) AddedFields() []string {
	var fields []string
	if m.addlatitude != nil {
		fields = append(fields, event.FieldLatitude)
	}
	if m.addlongitude != nil {
		fields = append(fields, event.FieldLongitude)
	}
	if m.adddefault_points_allocated != nil {
		fields = append(fields, event.FieldDefaultPointsAllocated)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *EventMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case event.FieldLatitude:
		return m.AddedLatitude()
	case event.FieldLongitude:
		return m.AddedLongitude()
	case event.FieldDefaultPointsAllocated:
		return m.AddedDefaultPointsAllocated()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *EventMutation) AddField(name string, value ent.Value) error {
	switch name {
	case event.FieldLatitude:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddLatitude(v)
		return nil
	case event.FieldLongitude:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddLongitude(v)
		return nil
	case event.FieldDefaultPointsAllocated:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDefaultPointsAllocated(v)
		return nil
	}
	return fmt.Errorf("unknown Event numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *EventMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *EventMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *EventMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Event nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *EventMutation) ResetField(name string) error {
	switch name {
	case event.FieldName:
		m.ResetName()
		return nil
	case event.FieldDescription:
		m.ResetDescription()
		return nil
	case event.FieldDate:
		m.ResetDate()
		return nil
	case event.FieldLatitude:
		m.ResetLatitude()
		return nil
	case event.FieldLongitude:
		m.ResetLongitude()
		return nil
	case event.FieldDefaultPointsAllocated:
		m.ResetDefaultPointsAllocated()
		return nil
	}
	return fmt.Errorf("unknown Event field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *EventMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.point_allocations != nil {
		edges = append(edges, event.EdgePointAllocations)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *EventMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case event.EdgePointAllocations:
		ids := make([]ent.Value, 0, len(m.point_allocations))
		for id := range m.point_allocations {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *EventMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedpoint_allocations != nil {
		edges = append(edges, event.EdgePointAllocations)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *EventMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case event.EdgePointAllocations:
		ids := make([]ent.Value, 0, len(m.removedpoint_allocations))
		for id := range m.removedpoint_allocations {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *EventMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedpoint_allocations {
		edges = append(edges, event.EdgePointAllocations)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *EventMutation) EdgeCleared(name string) bool {
	switch name {
	case event.EdgePointAllocations:
		return m.clearedpoint_allocations
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *EventMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Event unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *EventMutation) ResetEdge(name string) error {
	switch name {
	case event.EdgePointAllocations:
		m.ResetPointAllocations()
		return nil
	}
	return fmt.Errorf("unknown Event edge %s", name)
}

// MemberMutation represents an operation that mutates the Member nodes in the graph.
type MemberMutation struct {
	config
	op                       Op
	typ                      string
	id                       *int
	name                     *string
	email                    *string
	phone                    *string
	mailing_address          *string
	call_sign                *string
	frn                      *string
	is_active                *bool
	is_silent_key            *bool
	license_class            *string
	clearedFields            map[string]struct{}
	point_allocations        map[int]struct{}
	removedpoint_allocations map[int]struct{}
	clearedpoint_allocations bool
	done                     bool
	oldValue                 func(context.Context) (*Member, error)
	predicates               []predicate.Member
}

var _ ent.Mutation = (*MemberMutation)(nil)

// memberOption allows management of the mutation configuration using functional options.
type memberOption func(*MemberMutation)

// newMemberMutation creates new mutation for the Member entity.
func newMemberMutation(c config, op Op, opts ...memberOption) *MemberMutation {
	m := &MemberMutation{
		config:        c,
		op:            op,
		typ:           TypeMember,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withMemberID sets the ID field of the mutation.
func withMemberID(id int) memberOption {
	return func(m *MemberMutation) {
		var (
			err   error
			once  sync.Once
			value *Member
		)
		m.oldValue = func(ctx context.Context) (*Member, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Member.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withMember sets the old Member of the mutation.
func withMember(node *Member) memberOption {
	return func(m *MemberMutation) {
		m.oldValue = func(context.Context) (*Member, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m MemberMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m MemberMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *MemberMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *MemberMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Member.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *MemberMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *MemberMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Member entity.
// If the Member object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MemberMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *MemberMutation) ResetName() {
	m.name = nil
}

// SetEmail sets the "email" field.
func (m *MemberMutation) SetEmail(s string) {
	m.email = &s
}

// Email returns the value of the "email" field in the mutation.
func (m *MemberMutation) Email() (r string, exists bool) {
	v := m.email
	if v == nil {
		return
	}
	return *v, true
}

// OldEmail returns the old "email" field's value of the Member entity.
// If the Member object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MemberMutation) OldEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmail: %w", err)
	}
	return oldValue.Email, nil
}

// ResetEmail resets all changes to the "email" field.
func (m *MemberMutation) ResetEmail() {
	m.email = nil
}

// SetPhone sets the "phone" field.
func (m *MemberMutation) SetPhone(s string) {
	m.phone = &s
}

// Phone returns the value of the "phone" field in the mutation.
func (m *MemberMutation) Phone() (r string, exists bool) {
	v := m.phone
	if v == nil {
		return
	}
	return *v, true
}

// OldPhone returns the old "phone" field's value of the Member entity.
// If the Member object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MemberMutation) OldPhone(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPhone is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPhone requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPhone: %w", err)
	}
	return oldValue.Phone, nil
}

// ClearPhone clears the value of the "phone" field.
func (m *MemberMutation) ClearPhone() {
	m.phone = nil
	m.clearedFields[member.FieldPhone] = struct{}{}
}

// PhoneCleared returns if the "phone" field was cleared in this mutation.
func (m *MemberMutation) PhoneCleared() bool {
	_, ok := m.clearedFields[member.FieldPhone]
	return ok
}

// ResetPhone resets all changes to the "phone" field.
func (m *MemberMutation) ResetPhone() {
	m.phone = nil
	delete(m.clearedFields, member.FieldPhone)
}

// SetMailingAddress sets the "mailing_address" field.
func (m *MemberMutation) SetMailingAddress(s string) {
	m.mailing_address = &s
}

// MailingAddress returns the value of the "mailing_address" field in the mutation.
func (m *MemberMutation) MailingAddress() (r string, exists bool) {
	v := m.mailing_address
	if v == nil {
		return
	}
	return *v, true
}

// OldMailingAddress returns the old "mailing_address" field's value of the Member entity.
// If the Member object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MemberMutation) OldMailingAddress(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMailingAddress is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMailingAddress requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMailingAddress: %w", err)
	}
	return oldValue.MailingAddress, nil
}

// ClearMailingAddress clears the value of the "mailing_address" field.
func (m *MemberMutation) ClearMailingAddress() {
	m.mailing_address = nil
	m.clearedFields[member.FieldMailingAddress] = struct{}{}
}

// MailingAddressCleared returns if the "mailing_address" field was cleared in this mutation.
func (m *MemberMutation) MailingAddressCleared() bool {
	_, ok := m.clearedFields[member.FieldMailingAddress]
	return ok
}

// ResetMailingAddress resets all changes to the "mailing_address" field.
func (m *MemberMutation) ResetMailingAddress() {
	m.mailing_address = nil
	delete(m.clearedFields, member.FieldMailingAddress)
}

// SetCallSign sets the "call_sign" field.
func (m *MemberMutation) SetCallSign(s string) {
	m.call_sign = &s
}

// CallSign returns the value of the "call_sign" field in the mutation.
func (m *MemberMutation) CallSign() (r string, exists bool) {
	v := m.call_sign
	if v == nil {
		return
	}
	return *v, true
}

// OldCallSign returns the old "call_sign" field's value of the Member entity.
// If the Member object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MemberMutation) OldCallSign(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCallSign is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCallSign requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCallSign: %w", err)
	}
	return oldValue.CallSign, nil
}

// ClearCallSign clears the value of the "call_sign" field.
func (m *MemberMutation) ClearCallSign() {
	m.call_sign = nil
	m.clearedFields[member.FieldCallSign] = struct{}{}
}

// CallSignCleared returns if the "call_sign" field was cleared in this mutation.
func (m *MemberMutation) CallSignCleared() bool {
	_, ok := m.clearedFields[member.FieldCallSign]
	return ok
}

// ResetCallSign resets all changes to the "call_sign" field.
func (m *MemberMutation) ResetCallSign() {
	m.call_sign = nil
	delete(m.clearedFields, member.FieldCallSign)
}

// SetFrn sets the "frn" field.
func (m *MemberMutation) SetFrn(s string) {
	m.frn = &s
}

// Frn returns the value of the "frn" field in the mutation.
func (m *MemberMutation) Frn() (r string, exists bool) {
	v := m.frn
	if v == nil {
		return
	}
	return *v, true
}

// OldFrn returns the old "frn" field's value of the Member entity.
// If the Member object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MemberMutation) OldFrn(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFrn is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFrn requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFrn: %w", err)
	}
	return oldValue.Frn, nil
}

// ClearFrn clears the value of the "frn" field.
func (m *MemberMutation) ClearFrn() {
	m.frn = nil
	m.clearedFields[member.FieldFrn] = struct{}{}
}

// FrnCleared returns if the "frn" field was cleared in this mutation.
func (m *MemberMutation) FrnCleared() bool {
	_, ok := m.clearedFields[member.FieldFrn]
	return ok
}

// ResetFrn resets all changes to the "frn" field.
func (m *MemberMutation) ResetFrn() {
	m.frn = nil
	delete(m.clearedFields, member.FieldFrn)
}

// SetIsActive sets the "is_active" field.
func (m *MemberMutation) SetIsActive(b bool) {
	m.is_active = &b
}

// IsActive returns the value of the "is_active" field in the mutation.
func (m *MemberMutation) IsActive() (r bool, exists bool) {
	v := m.is_active
	if v == nil {
		return
	}
	return *v, true
}

// OldIsActive returns the old "is_active" field's value of the Member entity.
// If the Member object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MemberMutation) OldIsActive(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsActive is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsActive requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsActive: %w", err)
	}
	return oldValue.IsActive, nil
}

// ResetIsActive resets all changes to the "is_active" field.
func (m *MemberMutation) ResetIsActive() {
	m.is_active = nil
}

// SetIsSilentKey sets the "is_silent_key" field.
func (m *MemberMutation) SetIsSilentKey(b bool) {
	m.is_silent_key = &b
}

// IsSilentKey returns the value of the "is_silent_key" field in the mutation.
func (m *MemberMutation) IsSilentKey() (r bool, exists bool) {
	v := m.is_silent_key
	if v == nil {
		return
	}
	return *v, true
}

// OldIsSilentKey returns the old "is_silent_key" field's value of the Member entity.
// If the Member object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MemberMutation) OldIsSilentKey(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsSilentKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsSilentKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsSilentKey: %w", err)
	}
	return oldValue.IsSilentKey, nil
}

// ResetIsSilentKey resets all changes to the "is_silent_key" field.
func (m *MemberMutation) ResetIsSilentKey() {
	m.is_silent_key = nil
}

// SetLicenseClass sets the "license_class" field.
func (m *MemberMutation) SetLicenseClass(s string) {
	m.license_class = &s
}

// LicenseClass returns the value of the "license_class" field in the mutation.
func (m *MemberMutation) LicenseClass() (r string, exists bool) {
	v := m.license_class
	if v == nil {
		return
	}
	return *v, true
}

// OldLicenseClass returns the old "license_class" field's value of the Member entity.
// If the Member object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MemberMutation) OldLicenseClass(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLicenseClass is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLicenseClass requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLicenseClass: %w", err)
	}
	return oldValue.LicenseClass, nil
}

// ClearLicenseClass clears the value of the "license_class" field.
func (m *MemberMutation) ClearLicenseClass() {
	m.license_class = nil
	m.clearedFields[member.FieldLicenseClass] = struct{}{}
}

// LicenseClassCleared returns if the "license_class" field was cleared in this mutation.
func (m *MemberMutation) LicenseClassCleared() bool {
	_, ok := m.clearedFields[member.FieldLicenseClass]
	return ok
}

// ResetLicenseClass resets all changes to the "license_class" field.
func (m *MemberMutation) ResetLicenseClass() {
	m.license_class = nil
	delete(m.clearedFields, member.FieldLicenseClass)
}

// AddPointAllocationIDs adds the "point_allocations" edge to the PointAllocation entity by ids.
func (m *MemberMutation) AddPointAllocationIDs(ids ...int) {
	if m.point_allocations == nil {
		m.point_allocations = make(map[int]struct{})
	}
	for i := range ids {
		m.point_allocations[ids[i]] = struct{}{}
	}
}

// ClearPointAllocations clears the "point_allocations" edge to the PointAllocation entity.
func (m *MemberMutation) ClearPointAllocations() {
	m.clearedpoint_allocations = true
}

// PointAllocationsCleared reports if the "point_allocations" edge to the PointAllocation entity was cleared.
func (m *MemberMutation) PointAllocationsCleared() bool {
	return m.clearedpoint_allocations
}

// RemovePointAllocationIDs removes the "point_allocations" edge to the PointAllocation entity by IDs.
func (m *MemberMutation) RemovePointAllocationIDs(ids ...int) {
	if m.removedpoint_allocations == nil {
		m.removedpoint_allocations = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.point_allocations, ids[i])
		m.removedpoint_allocations[ids[i]] = struct{}{}
	}
}

// RemovedPointAllocations returns the removed IDs of the "point_allocations" edge to the PointAllocation entity.
func (m *MemberMutation) RemovedPointAllocationsIDs() (ids []int) {
	for id := range m.removedpoint_allocations {
		ids = append(ids, id)
	}
	return
}

// PointAllocationsIDs returns the "point_allocations" edge IDs in the mutation.
func (m *MemberMutation) PointAllocationsIDs() (ids []int) {
	for id := range m.point_allocations {
		ids = append(ids, id)
	}
	return
}

// ResetPointAllocations resets all changes to the "point_allocations" edge.
func (m *MemberMutation) ResetPointAllocations() {
	m.point_allocations = nil
	m.clearedpoint_allocations = false
	m.removedpoint_allocations = nil
}

// Where appends a list predicates to the MemberMutation builder.
func (m *MemberMutation) Where(ps ...predicate.Member) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the MemberMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *MemberMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Member, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *MemberMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *MemberMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Member).
func (m *MemberMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *MemberMutation) Fields() []string {
	fields := make([]string, 0, 9)
	if m.name != nil {
		fields = append(fields, member.FieldName)
	}
	if m.email != nil {
		fields = append(fields, member.FieldEmail)
	}
	if m.phone != nil {
		fields = append(fields, member.FieldPhone)
	}
	if m.mailing_address != nil {
		fields = append(fields, member.FieldMailingAddress)
	}
	if m.call_sign != nil {
		fields = append(fields, member.FieldCallSign)
	}
	if m.frn != nil {
		fields = append(fields, member.FieldFrn)
	}
	if m.is_active != nil {
		fields = append(fields, member.FieldIsActive)
	}
	if m.is_silent_key != nil {
		fields = append(fields, member.FieldIsSilentKey)
	}
	if m.license_class != nil {
		fields = append(fields, member.FieldLicenseClass)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *MemberMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case member.FieldName:
		return m.Name()
	case member.FieldEmail:
		return m.Email()
	case member.FieldPhone:
		return m.Phone()
	case member.FieldMailingAddress:
		return m.MailingAddress()
	case member.FieldCallSign:
		return m.CallSign()
	case member.FieldFrn:
		return m.Frn()
	case member.FieldIsActive:
		return m.IsActive()
	case member.FieldIsSilentKey:
		return m.IsSilentKey()
	case member.FieldLicenseClass:
		return m.LicenseClass()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *MemberMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case member.FieldName:
		return m.OldName(ctx)
	case member.FieldEmail:
		return m.OldEmail(ctx)
	case member.FieldPhone:
		return m.OldPhone(ctx)
	case member.FieldMailingAddress:
		return m.OldMailingAddress(ctx)
	case member.FieldCallSign:
		return m.OldCallSign(ctx)
	case member.FieldFrn:
		return m.OldFrn(ctx)
	case member.FieldIsActive:
		return m.OldIsActive(ctx)
	case member.FieldIsSilentKey:
		return m.OldIsSilentKey(ctx)
	case member.FieldLicenseClass:
		return m.OldLicenseClass(ctx)
	}
	return nil, fmt.Errorf("unknown Member field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MemberMutation) SetField(name string, value ent.Value) error {
	switch name {
	case member.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case member.FieldEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmail(v)
		return nil
	case member.FieldPhone:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPhone(v)
		return nil
	case member.FieldMailingAddress:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMailingAddress(v)
		return nil
	case member.FieldCallSign:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCallSign(v)
		return nil
	case member.FieldFrn:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFrn(v)
		return nil
	case member.FieldIsActive:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsActive(v)
		return nil
	case member.FieldIsSilentKey:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsSilentKey(v)
		return nil
	case member.FieldLicenseClass:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLicenseClass(v)
		return nil
	}
	return fmt.Errorf("unknown Member field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *MemberMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *MemberMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MemberMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Member numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *MemberMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(member.FieldPhone) {
		fields = append(fields, member.FieldPhone)
	}
	if m.FieldCleared(member.FieldMailingAddress) {
		fields = append(fields, member.FieldMailingAddress)
	}
	if m.FieldCleared(member.FieldCallSign) {
		fields = append(fields, member.FieldCallSign)
	}
	if m.FieldCleared(member.FieldFrn) {
		fields = append(fields, member.FieldFrn)
	}
	if m.FieldCleared(member.FieldLicenseClass) {
		fields = append(fields, member.FieldLicenseClass)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *MemberMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *MemberMutation) ClearField(name string) error {
	switch name {
	case member.FieldPhone:
		m.ClearPhone()
		return nil
	case member.FieldMailingAddress:
		m.ClearMailingAddress()
		return nil
	case member.FieldCallSign:
		m.ClearCallSign()
		return nil
	case member.FieldFrn:
		m.ClearFrn()
		return nil
	case member.FieldLicenseClass:
		m.ClearLicenseClass()
		return nil
	}
	return fmt.Errorf("unknown Member nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *MemberMutation) ResetField(name string) error {
	switch name {
	case member.FieldName:
		m.ResetName()
		return nil
	case member.FieldEmail:
		m.ResetEmail()
		return nil
	case member.FieldPhone:
		m.ResetPhone()
		return nil
	case member.FieldMailingAddress:
		m.ResetMailingAddress()
		return nil
	case member.FieldCallSign:
		m.ResetCallSign()
		return nil
	case member.FieldFrn:
		m.ResetFrn()
		return nil
	case member.FieldIsActive:
		m.ResetIsActive()
		return nil
	case member.FieldIsSilentKey:
		m.ResetIsSilentKey()
		return nil
	case member.FieldLicenseClass:
		m.ResetLicenseClass()
		return nil
	}
	return fmt.Errorf("unknown Member field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *MemberMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.point_allocations != nil {
		edges = append(edges, member.EdgePointAllocations)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *MemberMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case member.EdgePointAllocations:
		ids := make([]ent.Value, 0, len(m.point_allocations))
		for id := range m.point_allocations {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *MemberMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedpoint_allocations != nil {
		edges = append(edges, member.EdgePointAllocations)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *MemberMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case member.EdgePointAllocations:
		ids := make([]ent.Value, 0, len(m.removedpoint_allocations))
		for id := range m.removedpoint_allocations {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *MemberMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedpoint_allocations {
		edges = append(edges, member.EdgePointAllocations)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *MemberMutation) EdgeCleared(name string) bool {
	switch name {
	case member.EdgePointAllocations:
		return m.clearedpoint_allocations
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *MemberMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Member unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *MemberMutation) ResetEdge(name string) error {
	switch name {
	case member.EdgePointAllocations:
		m.ResetPointAllocations()
		return nil
	}
	return fmt.Errorf("unknown Member edge %s", name)
}

// PointAllocationMutation represents an operation that mutates the PointAllocation nodes in the graph.
type PointAllocationMutation struct {
	config
	op            Op
	typ           string
	id            *int
	points        *int
	addpoints     *int
	notes         *string
	created_at    *time.Time
	clearedFields map[string]struct{}
	event         *int
	clearedevent  bool
	member        *int
	clearedmember bool
	done          bool
	oldValue      func(context.Context) (*PointAllocation, error)
	predicates    []predicate.PointAllocation
}

var _ ent.Mutation = (*PointAllocationMutation)(nil)

// pointallocationOption allows management of the mutation configuration using functional options.
type pointallocationOption func(*PointAllocationMutation)

// newPointAllocationMutation creates new mutation for the PointAllocation entity.
func newPointAllocationMutation(c config, op Op, opts ...pointallocationOption) *PointAllocationMutation {
	m := &PointAllocationMutation{
		config:        c,
		op:            op,
		typ:           TypePointAllocation,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPointAllocationID sets the ID field of the mutation.
func withPointAllocationID(id int) pointallocationOption {
	return func(m *PointAllocationMutation) {
		var (
			err   error
			once  sync.Once
			value *PointAllocation
		)
		m.oldValue = func(ctx context.Context) (*PointAllocation, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().PointAllocation.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPointAllocation sets the old PointAllocation of the mutation.
func withPointAllocation(node *PointAllocation) pointallocationOption {
	return func(m *PointAllocationMutation) {
		m.oldValue = func(context.Context) (*PointAllocation, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PointAllocationMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PointAllocationMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PointAllocationMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PointAllocationMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().PointAllocation.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetPoints sets the "points" field.
func (m *PointAllocationMutation) SetPoints(i int) {
	m.points = &i
	m.addpoints = nil
}

// Points returns the value of the "points" field in the mutation.
func (m *PointAllocationMutation) Points() (r int, exists bool) {
	v := m.points
	if v == nil {
		return
	}
	return *v, true
}

// OldPoints returns the old "points" field's value of the PointAllocation entity.
// If the PointAllocation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PointAllocationMutation) OldPoints(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPoints is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPoints requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPoints: %w", err)
	}
	return oldValue.Points, nil
}

// AddPoints adds i to the "points" field.
func (m *PointAllocationMutation) AddPoints(i int) {
	if m.addpoints != nil {
		*m.addpoints += i
	} else {
		m.addpoints = &i
	}
}

// AddedPoints returns the value that was added to the "points" field in this mutation.
func (m *PointAllocationMutation) AddedPoints() (r int, exists bool) {
	v := m.addpoints
	if v == nil {
		return
	}
	return *v, true
}

// ResetPoints resets all changes to the "points" field.
func (m *PointAllocationMutation) ResetPoints() {
	m.points = nil
	m.addpoints = nil
}

// SetNotes sets the "notes" field.
func (m *PointAllocationMutation) SetNotes(s string) {
	m.notes = &s
}

// Notes returns the value of the "notes" field in the mutation.
func (m *PointAllocationMutation) Notes() (r string, exists bool) {
	v := m.notes
	if v == nil {
		return
	}
	return *v, true
}

// OldNotes returns the old "notes" field's value of the PointAllocation entity.
// If the PointAllocation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PointAllocationMutation) OldNotes(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNotes is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNotes requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNotes: %w", err)
	}
	return oldValue.Notes, nil
}

// ClearNotes clears the value of the "notes" field.
func (m *PointAllocationMutation) ClearNotes() {
	m.notes = nil
	m.clearedFields[pointallocation.FieldNotes] = struct{}{}
}

// NotesCleared returns if the "notes" field was cleared in this mutation.
func (m *PointAllocationMutation) NotesCleared() bool {
	_, ok := m.clearedFields[pointallocation.FieldNotes]
	return ok
}

// ResetNotes resets all changes to the "notes" field.
func (m *PointAllocationMutation) ResetNotes() {
	m.notes = nil
	delete(m.clearedFields, pointallocation.FieldNotes)
}

// SetCreatedAt sets the "created_at" field.
func (m *PointAllocationMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *PointAllocationMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the PointAllocation entity.
// If the PointAllocation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PointAllocationMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *PointAllocationMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetEventID sets the "event" edge to the Event entity by id.
func (m *PointAllocationMutation) SetEventID(id int) {
	m.event = &id
}

// ClearEvent clears the "event" edge to the Event entity.
func (m *PointAllocationMutation) ClearEvent() {
	m.clearedevent = true
}

// EventCleared reports if the "event" edge to the Event entity was cleared.
func (m *PointAllocationMutation) EventCleared() bool {
	return m.clearedevent
}

// EventID returns the "event" edge ID in the mutation.
func (m *PointAllocationMutation) EventID() (id int, exists bool) {
	if m.event != nil {
		return *m.event, true
	}
	return
}

// EventIDs returns the "event" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// EventID instead. It exists only for internal usage by the builders.
func (m *PointAllocationMutation) EventIDs() (ids []int) {
	if id := m.event; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetEvent resets all changes to the "event" edge.
func (m *PointAllocationMutation) ResetEvent() {
	m.event = nil
	m.clearedevent = false
}

// SetMemberID sets the "member" edge to the Member entity by id.
func (m *PointAllocationMutation) SetMemberID(id int) {
	m.member = &id
}

// ClearMember clears the "member" edge to the Member entity.
func (m *PointAllocationMutation) ClearMember() {
	m.clearedmember = true
}

// MemberCleared reports if the "member" edge to the Member entity was cleared.
func (m *PointAllocationMutation) MemberCleared() bool {
	return m.clearedmember
}

// MemberID returns the "member" edge ID in the mutation.
func (m *PointAllocationMutation) MemberID() (id int, exists bool) {
	if m.member != nil {
		return *m.member, true
	}
	return
}

// MemberIDs returns the "member" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// MemberID instead. It exists only for internal usage by the builders.
func (m *PointAllocationMutation) MemberIDs() (ids []int) {
	if id := m.member; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetMember resets all changes to the "member" edge.
func (m *PointAllocationMutation) ResetMember() {
	m.member = nil
	m.clearedmember = false
}

// Where appends a list predicates to the PointAllocationMutation builder.
func (m *PointAllocationMutation) Where(ps ...predicate.PointAllocation) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PointAllocationMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PointAllocationMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.PointAllocation, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PointAllocationMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PointAllocationMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (PointAllocation).
func (m *PointAllocationMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PointAllocationMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.points != nil {
		fields = append(fields, pointallocation.FieldPoints)
	}
	if m.notes != nil {
		fields = append(fields, pointallocation.FieldNotes)
	}
	if m.created_at != nil {
		fields = append(fields, pointallocation.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PointAllocationMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case pointallocation.FieldPoints:
		return m.Points()
	case pointallocation.FieldNotes:
		return m.Notes()
	case pointallocation.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PointAllocationMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case pointallocation.FieldPoints:
		return m.OldPoints(ctx)
	case pointallocation.FieldNotes:
		return m.OldNotes(ctx)
	case pointallocation.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown PointAllocation field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PointAllocationMutation) SetField(name string, value ent.Value) error {
	switch name {
	case pointallocation.FieldPoints:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPoints(v)
		return nil
	case pointallocation.FieldNotes:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNotes(v)
		return nil
	case pointallocation.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown PointAllocation field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PointAllocationMutation) AddedFields() []string {
	var fields []string
	if m.addpoints != nil {
		fields = append(fields, pointallocation.FieldPoints)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PointAllocationMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case pointallocation.FieldPoints:
		return m.AddedPoints()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PointAllocationMutation) AddField(name string, value ent.Value) error {
	switch name {
	case pointallocation.FieldPoints:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPoints(v)
		return nil
	}
	return fmt.Errorf("unknown PointAllocation numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PointAllocationMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(pointallocation.FieldNotes) {
		fields = append(fields, pointallocation.FieldNotes)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PointAllocationMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PointAllocationMutation) ClearField(name string) error {
	switch name {
	case pointallocation.FieldNotes:
		m.ClearNotes()
		return nil
	}
	return fmt.Errorf("unknown PointAllocation nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PointAllocationMutation) ResetField(name string) error {
	switch name {
	case pointallocation.FieldPoints:
		m.ResetPoints()
		return nil
	case pointallocation.FieldNotes:
		m.ResetNotes()
		return nil
	case pointallocation.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown PointAllocation field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PointAllocationMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.event != nil {
		edges = append(edges, pointallocation.EdgeEvent)
	}
	if m.member != nil {
		edges = append(edges, pointallocation.EdgeMember)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PointAllocationMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case pointallocation.EdgeEvent:
		if id := m.event; id != nil {
			return []ent.Value{*id}
		}
	case pointallocation.EdgeMember:
		if id := m.member; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PointAllocationMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PointAllocationMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PointAllocationMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedevent {
		edges = append(edges, pointallocation.EdgeEvent)
	}
	if m.clearedmember {
		edges = append(edges, pointallocation.EdgeMember)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PointAllocationMutation) EdgeCleared(name string) bool {
	switch name {
	case pointallocation.EdgeEvent:
		return m.clearedevent
	case pointallocation.EdgeMember:
		return m.clearedmember
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PointAllocationMutation) ClearEdge(name string) error {
	switch name {
	case pointallocation.EdgeEvent:
		m.ClearEvent()
		return nil
	case pointallocation.EdgeMember:
		m.ClearMember()
		return nil
	}
	return fmt.Errorf("unknown PointAllocation unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PointAllocationMutation) ResetEdge(name string) error {
	switch name {
	case pointallocation.EdgeEvent:
		m.ResetEvent()
		return nil
	case pointallocation.EdgeMember:
		m.ResetMember()
		return nil
	}
	return fmt.Errorf("unknown PointAllocation edge %s", name)
}
