// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/geowa4/rara-membership/ent/pointdeduction"
	"github.com/geowa4/rara-membership/ent/predicate"
)

// PointDeductionDelete is the builder for deleting a PointDeduction entity.
type PointDeductionDelete struct {
	config
	hooks    []Hook
	mutation *PointDeductionMutation
}

// Where appends a list predicates to the PointDeductionDelete builder.
func (_d *PointDeductionDelete) Where(ps ...predicate.PointDeduction) *PointDeductionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PointDeductionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PointDeductionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PointDeductionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(pointdeduction.Table, sqlgraph.NewFieldSpec(pointdeduction.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PointDeductionDeleteOne is the builder for deleting a single PointDeduction entity.
type PointDeductionDeleteOne struct {
	_d *PointDeductionDelete
}

// Where appends a list predicates to the PointDeductionDelete builder.
func (_d *PointDeductionDeleteOne) Where(ps ...predicate.PointDeduction) *PointDeductionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PointDeductionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pointdeduction.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PointDeductionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
