// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/geowa4/rara-membership/ent/event"
	"github.com/geowa4/rara-membership/ent/member"
	"github.com/geowa4/rara-membership/ent/pointallocation"
	"github.com/geowa4/rara-membership/ent/predicate"
)

// PointAllocationQuery is the builder for querying PointAllocation entities.
type PointAllocationQuery struct {
	config
	ctx        *QueryContext
	order      []pointallocation.OrderOption
	inters     []Interceptor
	predicates []predicate.PointAllocation
	withEvent  *EventQuery
	withMember *MemberQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PointAllocationQuery builder.
func (_q *PointAllocationQuery) Where(ps ...predicate.PointAllocation) *PointAllocationQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PointAllocationQuery) Limit(limit int) *PointAllocationQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PointAllocationQuery) Offset(offset int) *PointAllocationQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PointAllocationQuery) Unique(unique bool) *PointAllocationQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PointAllocationQuery) Order(o ...pointallocation.OrderOption) *PointAllocationQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryEvent chains the current query on the "event" edge.
func (_q *PointAllocationQuery) QueryEvent() *EventQuery {
	query := (&EventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pointallocation.Table, pointallocation.FieldID, selector),
			sqlgraph.To(event.Table, event.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, pointallocation.EventTable, pointallocation.EventColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMember chains the current query on the "member" edge.
func (_q *PointAllocationQuery) QueryMember() *MemberQuery {
	query := (&MemberClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pointallocation.Table, pointallocation.FieldID, selector),
			sqlgraph.To(member.Table, member.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, pointallocation.MemberTable, pointallocation.MemberColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PointAllocation entity from the query.
// Returns a *NotFoundError when no PointAllocation was found.
func (_q *PointAllocationQuery) First(ctx context.Context) (*PointAllocation, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pointallocation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PointAllocationQuery) FirstX(ctx context.Context) *PointAllocation {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PointAllocation ID from the query.
// Returns a *NotFoundError when no PointAllocation ID was found.
func (_q *PointAllocationQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pointallocation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PointAllocationQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PointAllocation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PointAllocation entity is found.
// Returns a *NotFoundError when no PointAllocation entities are found.
func (_q *PointAllocationQuery) Only(ctx context.Context) (*PointAllocation, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pointallocation.Label}
	default:
		return nil, &NotSingularError{pointallocation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PointAllocationQuery) OnlyX(ctx context.Context) *PointAllocation {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PointAllocation ID in the query.
// Returns a *NotSingularError when more than one PointAllocation ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PointAllocationQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pointallocation.Label}
	default:
		err = &NotSingularError{pointallocation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PointAllocationQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PointAllocations.
func (_q *PointAllocationQuery) All(ctx context.Context) ([]*PointAllocation, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PointAllocation, *PointAllocationQuery]()
	return withInterceptors[[]*PointAllocation](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PointAllocationQuery) AllX(ctx context.Context) []*PointAllocation {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PointAllocation IDs.
func (_q *PointAllocationQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(pointallocation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PointAllocationQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PointAllocationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PointAllocationQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PointAllocationQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PointAllocationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PointAllocationQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PointAllocationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PointAllocationQuery) Clone() *PointAllocationQuery {
	if _q == nil {
		return nil
	}
	return &PointAllocationQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]pointallocation.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.PointAllocation{}, _q.predicates...),
		withEvent:  _q.withEvent.Clone(),
		withMember: _q.withMember.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithEvent tells the query-builder to eager-load the nodes that are connected to
// the "event" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PointAllocationQuery) WithEvent(opts ...func(*EventQuery)) *PointAllocationQuery {
	query := (&EventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEvent = query
	return _q
}

// WithMember tells the query-builder to eager-load the nodes that are connected to
// the "member" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PointAllocationQuery) WithMember(opts ...func(*MemberQuery)) *PointAllocationQuery {
	query := (&MemberClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMember = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Points int `json:"points,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PointAllocation.Query().
//		GroupBy(pointallocation.FieldPoints).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PointAllocationQuery) GroupBy(field string, fields ...string) *PointAllocationGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PointAllocationGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = pointallocation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Points int `json:"points,omitempty"`
//	}
//
//	client.PointAllocation.Query().
//		Select(pointallocation.FieldPoints).
//		Scan(ctx, &v)
func (_q *PointAllocationQuery) Select(fields ...string) *PointAllocationSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PointAllocationSelect{PointAllocationQuery: _q}
	sbuild.label = pointallocation.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PointAllocationSelect configured with the given aggregations.
func (_q *PointAllocationQuery) Aggregate(fns ...AggregateFunc) *PointAllocationSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PointAllocationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !pointallocation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PointAllocationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PointAllocation, error) {
	var (
		nodes       = []*PointAllocation{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withEvent != nil,
			_q.withMember != nil,
		}
	)
	if _q.withEvent != nil || _q.withMember != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, pointallocation.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PointAllocation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PointAllocation{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withEvent; query != nil {
		if err := _q.loadEvent(ctx, query, nodes, nil,
			func(n *PointAllocation, e *Event) { n.Edges.Event = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMember; query != nil {
		if err := _q.loadMember(ctx, query, nodes, nil,
			func(n *PointAllocation, e *Member) { n.Edges.Member = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PointAllocationQuery) loadEvent(ctx context.Context, query *EventQuery, nodes []*PointAllocation, init func(*PointAllocation), assign func(*PointAllocation, *Event)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PointAllocation)
	for i := range nodes {
		if nodes[i].point_allocation_event == nil {
			continue
		}
		fk := *nodes[i].point_allocation_event
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(event.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "point_allocation_event" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PointAllocationQuery) loadMember(ctx context.Context, query *MemberQuery, nodes []*PointAllocation, init func(*PointAllocation), assign func(*PointAllocation, *Member)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PointAllocation)
	for i := range nodes {
		if nodes[i].point_allocation_member == nil {
			continue
		}
		fk := *nodes[i].point_allocation_member
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(member.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "point_allocation_member" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *PointAllocationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PointAllocationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(pointallocation.Table, pointallocation.Columns, sqlgraph.NewFieldSpec(pointallocation.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pointallocation.FieldID)
		for i := range fields {
			if fields[i] != pointallocation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PointAllocationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(pointallocation.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = pointallocation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PointAllocationGroupBy is the group-by builder for PointAllocation entities.
type PointAllocationGroupBy struct {
	selector
	build *PointAllocationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PointAllocationGroupBy) Aggregate(fns ...AggregateFunc) *PointAllocationGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PointAllocationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PointAllocationQuery, *PointAllocationGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PointAllocationGroupBy) sqlScan(ctx context.Context, root *PointAllocationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PointAllocationSelect is the builder for selecting fields of PointAllocation entities.
type PointAllocationSelect struct {
	*PointAllocationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PointAllocationSelect) Aggregate(fns ...AggregateFunc) *PointAllocationSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PointAllocationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PointAllocationQuery, *PointAllocationSelect](ctx, _s.PointAllocationQuery, _s, _s.inters, v)
}

func (_s *PointAllocationSelect) sqlScan(ctx context.Context, root *PointAllocationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
