// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/geowa4/rara-membership/ent/member"
	"github.com/geowa4/rara-membership/ent/pointdeduction"
	"github.com/geowa4/rara-membership/ent/predicate"
)

// PointDeductionUpdate is the builder for updating PointDeduction entities.
type PointDeductionUpdate struct {
	config
	hooks    []Hook
	mutation *PointDeductionMutation
}

// Where appends a list predicates to the PointDeductionUpdate builder.
func (_u *PointDeductionUpdate) Where(ps ...predicate.PointDeduction) *PointDeductionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPoints sets the "points" field.
func (_u *PointDeductionUpdate) SetPoints(v int) *PointDeductionUpdate {
	_u.mutation.ResetPoints()
	_u.mutation.SetPoints(v)
	return _u
}

// SetNillablePoints sets the "points" field if the given value is not nil.
func (_u *PointDeductionUpdate) SetNillablePoints(v *int) *PointDeductionUpdate {
	if v != nil {
		_u.SetPoints(*v)
	}
	return _u
}

// AddPoints adds value to the "points" field.
func (_u *PointDeductionUpdate) AddPoints(v int) *PointDeductionUpdate {
	_u.mutation.AddPoints(v)
	return _u
}

// SetNotes sets the "notes" field.
func (_u *PointDeductionUpdate) SetNotes(v string) *PointDeductionUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *PointDeductionUpdate) SetNillableNotes(v *string) *PointDeductionUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *PointDeductionUpdate) ClearNotes() *PointDeductionUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetMemberID sets the "member" edge to the Member entity by ID.
func (_u *PointDeductionUpdate) SetMemberID(id int) *PointDeductionUpdate {
	_u.mutation.SetMemberID(id)
	return _u
}

// SetMember sets the "member" edge to the Member entity.
func (_u *PointDeductionUpdate) SetMember(v *Member) *PointDeductionUpdate {
	return _u.SetMemberID(v.ID)
}

// Mutation returns the PointDeductionMutation object of the builder.
func (_u *PointDeductionUpdate) Mutation() *PointDeductionMutation {
	return _u.mutation
}

// ClearMember clears the "member" edge to the Member entity.
func (_u *PointDeductionUpdate) ClearMember() *PointDeductionUpdate {
	_u.mutation.ClearMember()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PointDeductionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PointDeductionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PointDeductionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PointDeductionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PointDeductionUpdate) check() error {
	if v, ok := _u.mutation.Points(); ok {
		if err := pointdeduction.PointsValidator(v); err != nil {
			return &ValidationError{Name: "points", err: fmt.Errorf(`ent: validator failed for field "PointDeduction.points": %w`, err)}
		}
	}
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PointDeduction.member"`)
	}
	return nil
}

func (_u *PointDeductionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pointdeduction.Table, pointdeduction.Columns, sqlgraph.NewFieldSpec(pointdeduction.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Points(); ok {
		_spec.SetField(pointdeduction.FieldPoints, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPoints(); ok {
		_spec.AddField(pointdeduction.FieldPoints, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(pointdeduction.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(pointdeduction.FieldNotes, field.TypeString)
	}
	if _u.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pointdeduction.MemberTable,
			Columns: []string{pointdeduction.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pointdeduction.MemberTable,
			Columns: []string{pointdeduction.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pointdeduction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PointDeductionUpdateOne is the builder for updating a single PointDeduction entity.
type PointDeductionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PointDeductionMutation
}

// SetPoints sets the "points" field.
func (_u *PointDeductionUpdateOne) SetPoints(v int) *PointDeductionUpdateOne {
	_u.mutation.ResetPoints()
	_u.mutation.SetPoints(v)
	return _u
}

// SetNillablePoints sets the "points" field if the given value is not nil.
func (_u *PointDeductionUpdateOne) SetNillablePoints(v *int) *PointDeductionUpdateOne {
	if v != nil {
		_u.SetPoints(*v)
	}
	return _u
}

// AddPoints adds value to the "points" field.
func (_u *PointDeductionUpdateOne) AddPoints(v int) *PointDeductionUpdateOne {
	_u.mutation.AddPoints(v)
	return _u
}

// SetNotes sets the "notes" field.
func (_u *PointDeductionUpdateOne) SetNotes(v string) *PointDeductionUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *PointDeductionUpdateOne) SetNillableNotes(v *string) *PointDeductionUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *PointDeductionUpdateOne) ClearNotes() *PointDeductionUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetMemberID sets the "member" edge to the Member entity by ID.
func (_u *PointDeductionUpdateOne) SetMemberID(id int) *PointDeductionUpdateOne {
	_u.mutation.SetMemberID(id)
	return _u
}

// SetMember sets the "member" edge to the Member entity.
func (_u *PointDeductionUpdateOne) SetMember(v *Member) *PointDeductionUpdateOne {
	return _u.SetMemberID(v.ID)
}

// Mutation returns the PointDeductionMutation object of the builder.
func (_u *PointDeductionUpdateOne) Mutation() *PointDeductionMutation {
	return _u.mutation
}

// ClearMember clears the "member" edge to the Member entity.
func (_u *PointDeductionUpdateOne) ClearMember() *PointDeductionUpdateOne {
	_u.mutation.ClearMember()
	return _u
}

// Where appends a list predicates to the PointDeductionUpdate builder.
func (_u *PointDeductionUpdateOne) Where(ps ...predicate.PointDeduction) *PointDeductionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PointDeductionUpdateOne) Select(field string, fields ...string) *PointDeductionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PointDeduction entity.
func (_u *PointDeductionUpdateOne) Save(ctx context.Context) (*PointDeduction, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PointDeductionUpdateOne) SaveX(ctx context.Context) *PointDeduction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PointDeductionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PointDeductionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PointDeductionUpdateOne) check() error {
	if v, ok := _u.mutation.Points(); ok {
		if err := pointdeduction.PointsValidator(v); err != nil {
			return &ValidationError{Name: "points", err: fmt.Errorf(`ent: validator failed for field "PointDeduction.points": %w`, err)}
		}
	}
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PointDeduction.member"`)
	}
	return nil
}

func (_u *PointDeductionUpdateOne) sqlSave(ctx context.Context) (_node *PointDeduction, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pointdeduction.Table, pointdeduction.Columns, sqlgraph.NewFieldSpec(pointdeduction.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PointDeduction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pointdeduction.FieldID)
		for _, f := range fields {
			if !pointdeduction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pointdeduction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Points(); ok {
		_spec.SetField(pointdeduction.FieldPoints, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPoints(); ok {
		_spec.AddField(pointdeduction.FieldPoints, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(pointdeduction.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(pointdeduction.FieldNotes, field.TypeString)
	}
	if _u.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pointdeduction.MemberTable,
			Columns: []string{pointdeduction.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pointdeduction.MemberTable,
			Columns: []string{pointdeduction.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PointDeduction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pointdeduction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
