// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/geowa4/rara-membership/ent/event"
	"github.com/geowa4/rara-membership/ent/member"
	"github.com/geowa4/rara-membership/ent/pointallocation"
)

// PointAllocation is the model entity for the PointAllocation schema.
type PointAllocation struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Number of points allocated to the member for the event
	Points int `json:"points,omitempty"`
	// Optional notes about the allocation
	Notes string `json:"notes,omitempty"`
	// When the allocation was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PointAllocationQuery when eager-loading is set.
	Edges                   PointAllocationEdges `json:"edges"`
	point_allocation_event  *int
	point_allocation_member *int
	selectValues            sql.SelectValues
}

// PointAllocationEdges holds the relations/edges for other nodes in the graph.
type PointAllocationEdges struct {
	// The event for which points are allocated
	Event *Event `json:"event,omitempty"`
	// The member receiving the points
	Member *Member `json:"member,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// EventOrErr returns the Event value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PointAllocationEdges) EventOrErr() (*Event, error) {
	if e.Event != nil {
		return e.Event, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: event.Label}
	}
	return nil, &NotLoadedError{edge: "event"}
}

// MemberOrErr returns the Member value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PointAllocationEdges) MemberOrErr() (*Member, error) {
	if e.Member != nil {
		return e.Member, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: member.Label}
	}
	return nil, &NotLoadedError{edge: "member"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PointAllocation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pointallocation.FieldID, pointallocation.FieldPoints:
			values[i] = new(sql.NullInt64)
		case pointallocation.FieldNotes:
			values[i] = new(sql.NullString)
		case pointallocation.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case pointallocation.ForeignKeys[0]: // point_allocation_event
			values[i] = new(sql.NullInt64)
		case pointallocation.ForeignKeys[1]: // point_allocation_member
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PointAllocation fields.
func (_m *PointAllocation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pointallocation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case pointallocation.FieldPoints:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field points", values[i])
			} else if value.Valid {
				_m.Points = int(value.Int64)
			}
		case pointallocation.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case pointallocation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case pointallocation.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field point_allocation_event", value)
			} else if value.Valid {
				_m.point_allocation_event = new(int)
				*_m.point_allocation_event = int(value.Int64)
			}
		case pointallocation.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field point_allocation_member", value)
			} else if value.Valid {
				_m.point_allocation_member = new(int)
				*_m.point_allocation_member = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PointAllocation.
// This includes values selected through modifiers, order, etc.
func (_m *PointAllocation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEvent queries the "event" edge of the PointAllocation entity.
func (_m *PointAllocation) QueryEvent() *EventQuery {
	return NewPointAllocationClient(_m.config).QueryEvent(_m)
}

// QueryMember queries the "member" edge of the PointAllocation entity.
func (_m *PointAllocation) QueryMember() *MemberQuery {
	return NewPointAllocationClient(_m.config).QueryMember(_m)
}

// Update returns a builder for updating this PointAllocation.
// Note that you need to call PointAllocation.Unwrap() before calling this method if this PointAllocation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PointAllocation) Update() *PointAllocationUpdateOne {
	return NewPointAllocationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PointAllocation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PointAllocation) Unwrap() *PointAllocation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PointAllocation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PointAllocation) String() string {
	var builder strings.Builder
	builder.WriteString("PointAllocation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("points=")
	builder.WriteString(fmt.Sprintf("%v", _m.Points))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PointAllocations is a parsable slice of PointAllocation.
type PointAllocations []*PointAllocation
