// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/geowa4/rara-membership/ent/event"
	"github.com/geowa4/rara-membership/ent/member"
	"github.com/geowa4/rara-membership/ent/pointallocation"
	"github.com/geowa4/rara-membership/ent/predicate"
)

// PointAllocationUpdate is the builder for updating PointAllocation entities.
type PointAllocationUpdate struct {
	config
	hooks    []Hook
	mutation *PointAllocationMutation
}

// Where appends a list predicates to the PointAllocationUpdate builder.
func (_u *PointAllocationUpdate) Where(ps ...predicate.PointAllocation) *PointAllocationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPoints sets the "points" field.
func (_u *PointAllocationUpdate) SetPoints(v int) *PointAllocationUpdate {
	_u.mutation.ResetPoints()
	_u.mutation.SetPoints(v)
	return _u
}

// SetNillablePoints sets the "points" field if the given value is not nil.
func (_u *PointAllocationUpdate) SetNillablePoints(v *int) *PointAllocationUpdate {
	if v != nil {
		_u.SetPoints(*v)
	}
	return _u
}

// AddPoints adds value to the "points" field.
func (_u *PointAllocationUpdate) AddPoints(v int) *PointAllocationUpdate {
	_u.mutation.AddPoints(v)
	return _u
}

// SetNotes sets the "notes" field.
func (_u *PointAllocationUpdate) SetNotes(v string) *PointAllocationUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *PointAllocationUpdate) SetNillableNotes(v *string) *PointAllocationUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *PointAllocationUpdate) ClearNotes() *PointAllocationUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetEventID sets the "event" edge to the Event entity by ID.
func (_u *PointAllocationUpdate) SetEventID(id int) *PointAllocationUpdate {
	_u.mutation.SetEventID(id)
	return _u
}

// SetEvent sets the "event" edge to the Event entity.
func (_u *PointAllocationUpdate) SetEvent(v *Event) *PointAllocationUpdate {
	return _u.SetEventID(v.ID)
}

// SetMemberID sets the "member" edge to the Member entity by ID.
func (_u *PointAllocationUpdate) SetMemberID(id int) *PointAllocationUpdate {
	_u.mutation.SetMemberID(id)
	return _u
}

// SetMember sets the "member" edge to the Member entity.
func (_u *PointAllocationUpdate) SetMember(v *Member) *PointAllocationUpdate {
	return _u.SetMemberID(v.ID)
}

// Mutation returns the PointAllocationMutation object of the builder.
func (_u *PointAllocationUpdate) Mutation() *PointAllocationMutation {
	return _u.mutation
}

// ClearEvent clears the "event" edge to the Event entity.
func (_u *PointAllocationUpdate) ClearEvent() *PointAllocationUpdate {
	_u.mutation.ClearEvent()
	return _u
}

// ClearMember clears the "member" edge to the Member entity.
func (_u *PointAllocationUpdate) ClearMember() *PointAllocationUpdate {
	_u.mutation.ClearMember()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PointAllocationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PointAllocationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PointAllocationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PointAllocationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PointAllocationUpdate) check() error {
	if v, ok := _u.mutation.Points(); ok {
		if err := pointallocation.PointsValidator(v); err != nil {
			return &ValidationError{Name: "points", err: fmt.Errorf(`ent: validator failed for field "PointAllocation.points": %w`, err)}
		}
	}
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PointAllocation.event"`)
	}
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PointAllocation.member"`)
	}
	return nil
}

func (_u *PointAllocationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pointallocation.Table, pointallocation.Columns, sqlgraph.NewFieldSpec(pointallocation.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Points(); ok {
		_spec.SetField(pointallocation.FieldPoints, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPoints(); ok {
		_spec.AddField(pointallocation.FieldPoints, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(pointallocation.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(pointallocation.FieldNotes, field.TypeString)
	}
	if _u.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pointallocation.EventTable,
			Columns: []string{pointallocation.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pointallocation.EventTable,
			Columns: []string{pointallocation.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pointallocation.MemberTable,
			Columns: []string{pointallocation.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pointallocation.MemberTable,
			Columns: []string{pointallocation.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pointallocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PointAllocationUpdateOne is the builder for updating a single PointAllocation entity.
type PointAllocationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PointAllocationMutation
}

// SetPoints sets the "points" field.
func (_u *PointAllocationUpdateOne) SetPoints(v int) *PointAllocationUpdateOne {
	_u.mutation.ResetPoints()
	_u.mutation.SetPoints(v)
	return _u
}

// SetNillablePoints sets the "points" field if the given value is not nil.
func (_u *PointAllocationUpdateOne) SetNillablePoints(v *int) *PointAllocationUpdateOne {
	if v != nil {
		_u.SetPoints(*v)
	}
	return _u
}

// AddPoints adds value to the "points" field.
func (_u *PointAllocationUpdateOne) AddPoints(v int) *PointAllocationUpdateOne {
	_u.mutation.AddPoints(v)
	return _u
}

// SetNotes sets the "notes" field.
func (_u *PointAllocationUpdateOne) SetNotes(v string) *PointAllocationUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *PointAllocationUpdateOne) SetNillableNotes(v *string) *PointAllocationUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *PointAllocationUpdateOne) ClearNotes() *PointAllocationUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetEventID sets the "event" edge to the Event entity by ID.
func (_u *PointAllocationUpdateOne) SetEventID(id int) *PointAllocationUpdateOne {
	_u.mutation.SetEventID(id)
	return _u
}

// SetEvent sets the "event" edge to the Event entity.
func (_u *PointAllocationUpdateOne) SetEvent(v *Event) *PointAllocationUpdateOne {
	return _u.SetEventID(v.ID)
}

// SetMemberID sets the "member" edge to the Member entity by ID.
func (_u *PointAllocationUpdateOne) SetMemberID(id int) *PointAllocationUpdateOne {
	_u.mutation.SetMemberID(id)
	return _u
}

// SetMember sets the "member" edge to the Member entity.
func (_u *PointAllocationUpdateOne) SetMember(v *Member) *PointAllocationUpdateOne {
	return _u.SetMemberID(v.ID)
}

// Mutation returns the PointAllocationMutation object of the builder.
func (_u *PointAllocationUpdateOne) Mutation() *PointAllocationMutation {
	return _u.mutation
}

// ClearEvent clears the "event" edge to the Event entity.
func (_u *PointAllocationUpdateOne) ClearEvent() *PointAllocationUpdateOne {
	_u.mutation.ClearEvent()
	return _u
}

// ClearMember clears the "member" edge to the Member entity.
func (_u *PointAllocationUpdateOne) ClearMember() *PointAllocationUpdateOne {
	_u.mutation.ClearMember()
	return _u
}

// Where appends a list predicates to the PointAllocationUpdate builder.
func (_u *PointAllocationUpdateOne) Where(ps ...predicate.PointAllocation) *PointAllocationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PointAllocationUpdateOne) Select(field string, fields ...string) *PointAllocationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PointAllocation entity.
func (_u *PointAllocationUpdateOne) Save(ctx context.Context) (*PointAllocation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PointAllocationUpdateOne) SaveX(ctx context.Context) *PointAllocation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PointAllocationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PointAllocationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PointAllocationUpdateOne) check() error {
	if v, ok := _u.mutation.Points(); ok {
		if err := pointallocation.PointsValidator(v); err != nil {
			return &ValidationError{Name: "points", err: fmt.Errorf(`ent: validator failed for field "PointAllocation.points": %w`, err)}
		}
	}
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PointAllocation.event"`)
	}
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PointAllocation.member"`)
	}
	return nil
}

func (_u *PointAllocationUpdateOne) sqlSave(ctx context.Context) (_node *PointAllocation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pointallocation.Table, pointallocation.Columns, sqlgraph.NewFieldSpec(pointallocation.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PointAllocation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pointallocation.FieldID)
		for _, f := range fields {
			if !pointallocation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pointallocation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Points(); ok {
		_spec.SetField(pointallocation.FieldPoints, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPoints(); ok {
		_spec.AddField(pointallocation.FieldPoints, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(pointallocation.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(pointallocation.FieldNotes, field.TypeString)
	}
	if _u.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pointallocation.EventTable,
			Columns: []string{pointallocation.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pointallocation.EventTable,
			Columns: []string{pointallocation.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pointallocation.MemberTable,
			Columns: []string{pointallocation.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pointallocation.MemberTable,
			Columns: []string{pointallocation.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PointAllocation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pointallocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
