// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/geowa4/rara-membership/ent/member"
	"github.com/geowa4/rara-membership/ent/pointdeduction"
)

// PointDeductionCreate is the builder for creating a PointDeduction entity.
type PointDeductionCreate struct {
	config
	mutation *PointDeductionMutation
	hooks    []Hook
}

// SetPoints sets the "points" field.
func (_c *PointDeductionCreate) SetPoints(v int) *PointDeductionCreate {
	_c.mutation.SetPoints(v)
	return _c
}

// SetNotes sets the "notes" field.
func (_c *PointDeductionCreate) SetNotes(v string) *PointDeductionCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *PointDeductionCreate) SetNillableNotes(v *string) *PointDeductionCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PointDeductionCreate) SetCreatedAt(v time.Time) *PointDeductionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PointDeductionCreate) SetNillableCreatedAt(v *time.Time) *PointDeductionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetMemberID sets the "member" edge to the Member entity by ID.
func (_c *PointDeductionCreate) SetMemberID(id int) *PointDeductionCreate {
	_c.mutation.SetMemberID(id)
	return _c
}

// SetMember sets the "member" edge to the Member entity.
func (_c *PointDeductionCreate) SetMember(v *Member) *PointDeductionCreate {
	return _c.SetMemberID(v.ID)
}

// Mutation returns the PointDeductionMutation object of the builder.
func (_c *PointDeductionCreate) Mutation() *PointDeductionMutation {
	return _c.mutation
}

// Save creates the PointDeduction in the database.
func (_c *PointDeductionCreate) Save(ctx context.Context) (*PointDeduction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PointDeductionCreate) SaveX(ctx context.Context) *PointDeduction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PointDeductionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PointDeductionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PointDeductionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := pointdeduction.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PointDeductionCreate) check() error {
	if _, ok := _c.mutation.Points(); !ok {
		return &ValidationError{Name: "points", err: errors.New(`ent: missing required field "PointDeduction.points"`)}
	}
	if v, ok := _c.mutation.Points(); ok {
		if err := pointdeduction.PointsValidator(v); err != nil {
			return &ValidationError{Name: "points", err: fmt.Errorf(`ent: validator failed for field "PointDeduction.points": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PointDeduction.created_at"`)}
	}
	if len(_c.mutation.MemberIDs()) == 0 {
		return &ValidationError{Name: "member", err: errors.New(`ent: missing required edge "PointDeduction.member"`)}
	}
	return nil
}

func (_c *PointDeductionCreate) sqlSave(ctx context.Context) (*PointDeduction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PointDeductionCreate) createSpec() (*PointDeduction, *sqlgraph.CreateSpec) {
	var (
		_node = &PointDeduction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pointdeduction.Table, sqlgraph.NewFieldSpec(pointdeduction.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Points(); ok {
		_spec.SetField(pointdeduction.FieldPoints, field.TypeInt, value)
		_node.Points = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(pointdeduction.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pointdeduction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pointdeduction.MemberTable,
			Columns: []string{pointdeduction.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.point_deduction_member = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PointDeductionCreateBulk is the builder for creating many PointDeduction entities in bulk.
type PointDeductionCreateBulk struct {
	config
	err      error
	builders []*PointDeductionCreate
}

// Save creates the PointDeduction entities in the database.
func (_c *PointDeductionCreateBulk) Save(ctx context.Context) ([]*PointDeduction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PointDeduction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PointDeductionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PointDeductionCreateBulk) SaveX(ctx context.Context) []*PointDeduction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PointDeductionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PointDeductionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
