// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/geowa4/rara-membership/ent/member"
	"github.com/geowa4/rara-membership/ent/pointdeduction"
)

// PointDeduction is the model entity for the PointDeduction schema.
type PointDeduction struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Number of points being deducted from the member
	Points int `json:"points,omitempty"`
	// Optional notes about the redemption
	Notes string `json:"notes,omitempty"`
	// When the deduction was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PointDeductionQuery when eager-loading is set.
	Edges                  PointDeductionEdges `json:"edges"`
	point_deduction_member *int
	selectValues           sql.SelectValues
}

// PointDeductionEdges holds the relations/edges for other nodes in the graph.
type PointDeductionEdges struct {
	// The member redeeming the points
	Member *Member `json:"member,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MemberOrErr returns the Member value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PointDeductionEdges) MemberOrErr() (*Member, error) {
	if e.Member != nil {
		return e.Member, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: member.Label}
	}
	return nil, &NotLoadedError{edge: "member"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PointDeduction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pointdeduction.FieldID, pointdeduction.FieldPoints:
			values[i] = new(sql.NullInt64)
		case pointdeduction.FieldNotes:
			values[i] = new(sql.NullString)
		case pointdeduction.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case pointdeduction.ForeignKeys[0]: // point_deduction_member
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PointDeduction fields.
func (_m *PointDeduction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pointdeduction.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case pointdeduction.FieldPoints:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field points", values[i])
			} else if value.Valid {
				_m.Points = int(value.Int64)
			}
		case pointdeduction.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case pointdeduction.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case pointdeduction.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field point_deduction_member", value)
			} else if value.Valid {
				_m.point_deduction_member = new(int)
				*_m.point_deduction_member = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PointDeduction.
// This includes values selected through modifiers, order, etc.
func (_m *PointDeduction) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMember queries the "member" edge of the PointDeduction entity.
func (_m *PointDeduction) QueryMember() *MemberQuery {
	return NewPointDeductionClient(_m.config).QueryMember(_m)
}

// Update returns a builder for updating this PointDeduction.
// Note that you need to call PointDeduction.Unwrap() before calling this method if this PointDeduction
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PointDeduction) Update() *PointDeductionUpdateOne {
	return NewPointDeductionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PointDeduction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PointDeduction) Unwrap() *PointDeduction {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PointDeduction is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PointDeduction) String() string {
	var builder strings.Builder
	builder.WriteString("PointDeduction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("points=")
	builder.WriteString(fmt.Sprintf("%v", _m.Points))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PointDeductions is a parsable slice of PointDeduction.
type PointDeductions []*PointDeduction
