// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/geowa4/rara-membership/ent/event"
	"github.com/geowa4/rara-membership/ent/member"
	"github.com/geowa4/rara-membership/ent/pointallocation"
)

// PointAllocationCreate is the builder for creating a PointAllocation entity.
type PointAllocationCreate struct {
	config
	mutation *PointAllocationMutation
	hooks    []Hook
}

// SetPoints sets the "points" field.
func (_c *PointAllocationCreate) SetPoints(v int) *PointAllocationCreate {
	_c.mutation.SetPoints(v)
	return _c
}

// SetNotes sets the "notes" field.
func (_c *PointAllocationCreate) SetNotes(v string) *PointAllocationCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *PointAllocationCreate) SetNillableNotes(v *string) *PointAllocationCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PointAllocationCreate) SetCreatedAt(v time.Time) *PointAllocationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PointAllocationCreate) SetNillableCreatedAt(v *time.Time) *PointAllocationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetEventID sets the "event" edge to the Event entity by ID.
func (_c *PointAllocationCreate) SetEventID(id int) *PointAllocationCreate {
	_c.mutation.SetEventID(id)
	return _c
}

// SetEvent sets the "event" edge to the Event entity.
func (_c *PointAllocationCreate) SetEvent(v *Event) *PointAllocationCreate {
	return _c.SetEventID(v.ID)
}

// SetMemberID sets the "member" edge to the Member entity by ID.
func (_c *PointAllocationCreate) SetMemberID(id int) *PointAllocationCreate {
	_c.mutation.SetMemberID(id)
	return _c
}

// SetMember sets the "member" edge to the Member entity.
func (_c *PointAllocationCreate) SetMember(v *Member) *PointAllocationCreate {
	return _c.SetMemberID(v.ID)
}

// Mutation returns the PointAllocationMutation object of the builder.
func (_c *PointAllocationCreate) Mutation() *PointAllocationMutation {
	return _c.mutation
}

// Save creates the PointAllocation in the database.
func (_c *PointAllocationCreate) Save(ctx context.Context) (*PointAllocation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PointAllocationCreate) SaveX(ctx context.Context) *PointAllocation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PointAllocationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PointAllocationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PointAllocationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := pointallocation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PointAllocationCreate) check() error {
	if _, ok := _c.mutation.Points(); !ok {
		return &ValidationError{Name: "points", err: errors.New(`ent: missing required field "PointAllocation.points"`)}
	}
	if v, ok := _c.mutation.Points(); ok {
		if err := pointallocation.PointsValidator(v); err != nil {
			return &ValidationError{Name: "points", err: fmt.Errorf(`ent: validator failed for field "PointAllocation.points": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PointAllocation.created_at"`)}
	}
	if len(_c.mutation.EventIDs()) == 0 {
		return &ValidationError{Name: "event", err: errors.New(`ent: missing required edge "PointAllocation.event"`)}
	}
	if len(_c.mutation.MemberIDs()) == 0 {
		return &ValidationError{Name: "member", err: errors.New(`ent: missing required edge "PointAllocation.member"`)}
	}
	return nil
}

func (_c *PointAllocationCreate) sqlSave(ctx context.Context) (*PointAllocation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PointAllocationCreate) createSpec() (*PointAllocation, *sqlgraph.CreateSpec) {
	var (
		_node = &PointAllocation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pointallocation.Table, sqlgraph.NewFieldSpec(pointallocation.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Points(); ok {
		_spec.SetField(pointallocation.FieldPoints, field.TypeInt, value)
		_node.Points = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(pointallocation.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pointallocation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pointallocation.EventTable,
			Columns: []string{pointallocation.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.point_allocation_event = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pointallocation.MemberTable,
			Columns: []string{pointallocation.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.point_allocation_member = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PointAllocationCreateBulk is the builder for creating many PointAllocation entities in bulk.
type PointAllocationCreateBulk struct {
	config
	err      error
	builders []*PointAllocationCreate
}

// Save creates the PointAllocation entities in the database.
func (_c *PointAllocationCreateBulk) Save(ctx context.Context) ([]*PointAllocation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PointAllocation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PointAllocationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PointAllocationCreateBulk) SaveX(ctx context.Context) []*PointAllocation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PointAllocationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PointAllocationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
