// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/geowa4/rara-membership/ent/member"
	"github.com/geowa4/rara-membership/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	memberFields := schema.Member{}.Fields()
	_ = memberFields
	// memberDescIsActive is the schema descriptor for is_active field.
	memberDescIsActive := memberFields[5].Descriptor()
	// member.DefaultIsActive holds the default value on creation for the is_active field.
	member.DefaultIsActive = memberDescIsActive.Default.(bool)
	// memberDescIsSilentKey is the schema descriptor for is_silent_key field.
	memberDescIsSilentKey := memberFields[6].Descriptor()
	// member.DefaultIsSilentKey holds the default value on creation for the is_silent_key field.
	member.DefaultIsSilentKey = memberDescIsSilentKey.Default.(bool)
}
