// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Member is the predicate function for member builders.
type Member func(*sql.Selector)

// PointAllocation is the predicate function for pointallocation builders.
type PointAllocation func(*sql.Selector)

// PointDeduction is the predicate function for pointdeduction builders.
type PointDeduction func(*sql.Selector)
